'use strict';
// STRATUM core: palette, sprites, item kinds and combat rules. World content lives in world.js.

// One char per color. '.' = transparent. Sprites get an auto dark outline.
const PAL = {
  k: '#0a0b10', w: '#f2f0ea', g: '#9ea2ad', G: '#4f535e', y: '#ffc23a', Y: '#b97a12',
  o: '#ff8a3c', O: '#fff1b0', r: '#ff3b4e', R: '#8f1626', b: '#4ec3ff', B: '#1a5a9e',
  c: '#6ff7ff', C: '#1a8fa0', v: '#39ff9e', V: '#0f5a3c', q: '#c9c6bd', Q: '#6e6b66',
  s: '#e8d6c8', S: '#a8928a', z: '#1d2029', Z: '#3a3f4f', h: '#08080c', t: '#15171e', T: '#262a36',
  p: '#b98cff', P: '#5a3a8f', e: '#dfe9f2', E: '#8aa2b8', n: '#c77a3a', N: '#5e3518', l: '#ffd9a0',
  // Decay: bone, bile, corpse skin, rust, oil.
  u: '#d6cba8', U: '#8c8266',
  i: '#a8c43a', I: '#4c5c1c', a: '#8e9a8a', A: '#4e5650', f: '#8a4526', d: '#1a2226',
};

const SPRITES = {
  heroD: [
    '................',
    '......TTTT......',
    '.....TThhTT.....',
    '.....ThhhhT.....',
    '.....cccccC.....',
    '.....hSssSh.....',
    '......hSSh......',
    '....zZZhhZZz....',
    '...zGGzZZzZGz...',
    '...GZzzZZzzZGgg.',
    '...GzzzZZzzZgGc.',
    '...SzzzZZzzz.G..',
    '....zzzZZzzz....',
    '....Gz.ZZ.zG....',
    '....z.hTTh.z....',
    '.....hh..hh.....',
  ],
  heroU: [
    '................',
    '......TTTT......',
    '.....TThhTT.....',
    '.....ThhhhT.....',
    '.....ThhhhT.....',
    '.....ThhhhT.....',
    '......hTTh......',
    '....zZZzzZZz....',
    '...zGGzzzzZGz...',
    '.ggGZzzZZzzzZG..',
    '.cGgzzzZZzzzzG..',
    '..G.zzzZZzzzzS..',
    '....zzzZZzzz....',
    '....Gz.ZZ.zG....',
    '....z.hTTh.z....',
    '.....hh..hh.....',
  ],
  heroR: [
    '................',
    '......TTTT......',
    '.....TThhhT.....',
    '.....ThhhhT.....',
    '.....ThhcccC....',
    '.....ThhSsS.....',
    '......ThSS......',
    '.....zZZhz......',
    '....zGGZzz......',
    '....GZzZzzSGGGg.',
    '...zGZzZzz..Gc..',
    '...zzZzZzzz.....',
    '..zzzZzZzzz.....',
    '..Gz.zZzzzzz....',
    '..z...hTThT.....',
    '.....hh...hh....',
  ],
  // Rho once a weapon is owned: the gun arm holds an upright blade (e/E are swapped per tier, see BLADE_TINT).
  heroDw: [
    '................',
    '......TTTT...e..',
    '.....TThhTT..eE.',
    '.....ThhhhT..eE.',
    '.....cccccC..eE.',
    '.....hSssSh..eE.',
    '......hSSh...eE.',
    '....zZZhhZZz.eE.',
    '...zGGzZZzZGqQQq',
    '...GZzzZZzzZGSS.',
    '...GzzzZZzzZg.N.',
    '...SzzzZZzzz....',
    '....zzzZZzzz....',
    '....Gz.ZZ.zG....',
    '....z.hTTh.z....',
    '.....hh..hh.....',
  ],
  heroUw: [
    '................',
    '..e...TTTT......',
    '.Ee..TThhTT.....',
    '.Ee..ThhhhT.....',
    '.Ee..ThhhhT.....',
    '.Ee..ThhhhT.....',
    '.Ee...hTTh......',
    '.Ee.zZZzzZZz....',
    'qQQqGGzzzzZGz...',
    '.SSGZzzZZzzzZG..',
    '.N.gzzzZZzzzzG..',
    '....zzzZZzzzzS..',
    '....zzzZZzzz....',
    '....Gz.ZZ.zG....',
    '....z.hTTh.z....',
    '.....hh..hh.....',
  ],
  heroRw: [
    '................',
    '......TTTT...e..',
    '.....TThhhT..eE.',
    '.....ThhhhT..eE.',
    '.....ThhcccC.eE.',
    '.....ThhSsS..eE.',
    '......ThSS...eE.',
    '.....zZZhz...eE.',
    '....zGGZzz..qQQq',
    '....GZzZzzSGGSS.',
    '...zGZzZzz....N.',
    '...zzZzZzzz.....',
    '..zzzZzZzzz.....',
    '..Gz.zZzzzzz....',
    '..z...hTThT.....',
    '.....hh...hh....',
  ],
  mite: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..G..........G..',
    '.G.G..TTTT..G.G.',
    '.G..GZgggGZG..G.',
    '.G.GZgGGGGZZG.G.',
    'G..TZZZrZZZZT..G',
    'G.G.TTZZZZTT.G.G',
    '...G.nG..Gn.G...',
    '..G...g..g...G..',
    '.......gg.......',
  ],
  miteB: [ // idle: legs mid-step
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...G........G...',
    '..G.G.TTTT.G.G..',
    '.G..GZgggGZG..G.',
    '.G.GZgGGGGZZG..G',
    '.G.TZZZrZZZZT.G.',
    'G.G.TTZZZZTT..G.',
    'G..G.nG..Gn..G..',
    '....G.g..g..G...',
    '......g..g......',
  ],
  wisp: [
    '.......TZG......',
    '.......TZG......',
    '........TZG.....',
    '.........TZG....',
    '.........TZG....',
    '........TZG.....',
    '.......TZG......',
    '......TZG.......',
    '.....TZG........',
    '.....TZG........',
    '.....TZGG.......',
    '......ggg.......',
    '......nNn.......',
    '.....n.w.n......',
    '....c.wcw.c.....',
    '...c..c.c..c....',
  ],
  wispB: [ // idle: the cable whips, the end arcs
    '.......TZG......',
    '.......TZG......',
    '.......TZG......',
    '........TZG.....',
    '.........TZG....',
    '..........TZG...',
    '..........TZG...',
    '.........TZG....',
    '........TZG.....',
    '.......TZG......',
    '......TZGG......',
    '......ggg.......',
    '.....nNn........',
    '...cn.w.n.......',
    '.cw.wcw.........',
    'c...c..c........',
  ],
  husk: [
    '........w.......',
    '.......qw.......',
    '.......qqc......',
    '......Qqw.......',
    '.......QG.......',
    '.......G........',
    '.....qqwqqc.....',
    '....qQ.GqwQ.....',
    '....Q.qGqQ.q....',
    '....q.QGq..Q....',
    '...Q..qGQ..q....',
    '...G..Q.q..G....',
    '...G..q.Q...G...',
    '..G...Q..q......',
    '......G..Q......',
    '.....GG..GG.....',
  ],
  sanitizer: [
    '.......ew.......',
    '......rrrr......',
    '......ewwE......',
    '.......gE.......',
    '.....ewwwwE.....',
    '....ewwwwweE....',
    '....w.wwweE.e...',
    '....w.ewwE..w...',
    '....g.ewwE..g...',
    '....w..eE...w...',
    '....w.ewwE..w...',
    '...ew.w..E..e...',
    '...g..w..E..gg..',
    '......w..E..g...',
    '......e..E......',
    '.....gg..gg.....',
  ],
  sanitizerL: [ // idle: visor glances left
    '.......ew.......',
    '.....rrrwE......',
    '......ewwE......',
    '.......gE.......',
    '.....ewwwwE.....',
    '....ewwwwweE....',
    '....w.wwweE.e...',
    '....w.ewwE..w...',
    '....g.ewwE..g...',
    '....w..eE...w...',
    '....w.ewwE..w...',
    '...ew.w..E..e...',
    '...g..w..E..gg..',
    '......w..E..g...',
    '......e..E......',
    '.....gg..gg.....',
  ],
  serpent: [
    '...........TZZT.',
    '..........ZGggGZ',
    '.........ZGvTTgt',
    '.........ZGTvTGg',
    '..........ZGGZt.',
    '.........gGg....',
    '........GgG.....',
    '.......TZZT.....',
    '......TZGvZ.....',
    '......TZZZT.....',
    '.......gGg......',
    '........GgG.....',
    '.........gGg....',
    '........TZZZT...',
    '........ZGvGZ...',
    '.........TZT....',
  ],
  serpentT: [ // idle: connector pins extend, LEDs flash
    '...........TZZT.',
    '..........ZGggGZ',
    '.........ZGwTTgg',
    '.........ZGTwTGg',
    '..........ZGGZg.',
    '.........gGg....',
    '........GgG.....',
    '.......TZZT.....',
    '......TZGwZ.....',
    '......TZZZT.....',
    '.......gGg......',
    '........GgG.....',
    '.........gGg....',
    '........TZZZT...',
    '........ZGwGZ...',
    '.........TZT....',
  ],
  mason: [
    '................',
    '......TZZT......',
    '......ZggZ......',
    '......ZrTZ......',
    '.....TZZZZT.....',
    '..TZZGgggggZZT..',
    '.ZgGZGGGGGGZGgZ.',
    '.ZGZ.yYyYyYy.ZGZ',
    '.ZGZ.YyYyYyY.ZGZ',
    '.TZT.ZGGGGGZ.TZT',
    '..g..ZZGGGZZ.G.G',
    '..G..TZZZZZT.G.G',
    '..g...ZG.GZ..GG.',
    '......ZG.GZ.....',
    '.....TZZ.ZZT....',
    '.....ZZZ.ZZZ....',
  ],
  masonB: [ // idle: sensor gutters out
    '................',
    '......TZZT......',
    '......ZggZ......',
    '......ZRTZ......',
    '.....TZZZZT.....',
    '..TZZGgggggZZT..',
    '.ZgGZGGGGGGZGgZ.',
    '.ZGZ.yYyYyYy.ZGZ',
    '.ZGZ.YyYyYyY.ZGZ',
    '.TZT.ZGGGGGZ.TZT',
    '..g..ZZGGGZZ.G.G',
    '..G..TZZZZZT.G.G',
    '..g...ZG.GZ..GG.',
    '......ZG.GZ.....',
    '.....TZZ.ZZT....',
    '.....ZZZ.ZZZ....',
  ],
  drone: [
    '................',
    '................',
    '.gggg.....gggg..',
    '...G.......G....',
    '...GZZZZZZZG....',
    '......ZGZ.......',
    '.....ZGgGZ......',
    '....ZGgGGZTZZZG.',
    '....ZGGGGZZGGGr.',
    '....TZZZZZ......',
    '.....T.G.T......',
    '.......G........',
    '.......g........',
    '................',
    '................',
    '................',
  ],
  droneB: [ // idle: rotors edge-on
    '................',
    '................',
    '..gg.......gg...',
    '...G.......G....',
    '...GZZZZZZZG....',
    '......ZGZ.......',
    '.....ZGgGZ......',
    '....ZGgGGZTZZZG.',
    '....ZGGGGZZGGGr.',
    '....TZZZZZ......',
    '.....T.G.T......',
    '.......G........',
    '.......g........',
    '................',
    '................',
    '................',
  ],
  turret: [
    '................',
    '....TZZZZZZT....',
    '...ZGggggggGZ...',
    '...ZGvTZZTGGZ...',
    '...ZGZhZZhZGZ...',
    '...TZZZZZZZZT...',
    '.....TZGGZT.....',
    '......ZGGZ......',
    '......TZZT......',
    '.....G.GG.G.....',
    '....G..G...G....',
    '...G...G....G...',
    '...G...G....G...',
    '..G....G.....G..',
    '..G....G.....G..',
    '.GG...GG.....GG.',
  ],
  turretL: [ // idle: swivelled left
    '................',
    '....TZZZZZZT....',
    '...ZGgggggggZ...',
    '.GGGZvZTZZGGZ...',
    '..TZZZZZZZZZZ...',
    '.GGGZZZZZZZZT...',
    '.....TZGGZT.....',
    '......ZGGZ......',
    '......TZZT......',
    '.....G.GG.G.....',
    '....G..G...G....',
    '...G...G....G...',
    '...G...G....G...',
    '..G....G.....G..',
    '..G....G.....G..',
    '.GG...GG.....GG.',
  ],
  hound: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..g.g.g.g.......',
    '..GgGgGgGZTZZ...',
    '.TZGZGZGZGGgGZG.',
    '..T.T.T.ZZTZrGGG',
    '..GZ.Z...GZ.Z...',
    '..G..Z...G..Z...',
    '.G...Z...G...Z..',
    '.G..Z...G....Z..',
    '..G.Z...G...Z...',
    '.GG.ZZ.GG...ZZ..',
  ],
  houndP: [ // idle: heat-sink fins flare, snout plates part
    '................',
    '................',
    '................',
    '................',
    '................',
    '..g.g.g.g.......',
    '..g.g.g.g.......',
    '..GgGgGgGZTZZGG.',
    '.TZGZGZGZGGgG...',
    '..T.T.T.ZZTZr...',
    '..GZ.Z...GZ.ZGG.',
    '..G..Z...G..Z...',
    '.G...Z...G...Z..',
    '.G..Z...G....Z..',
    '..G.Z...G...Z...',
    '.GG.ZZ.GG...ZZ..',
  ],
  ghost: [
    '................',
    '......eee.......',
    '......eEE.......',
    '......eEE.......',
    '.......E........',
    '.....eeEEE......',
    '....e.eEE.E.....',
    '....e.eEE.E.....',
    '..TTTTTTTTTTTT..',
    '......e.eEE.E...',
    '......e.eEE.E...',
    '....E.eEE.E.....',
    '......e.E.......',
    '......e.E.......',
    '..TTTTTTTTTTTT..',
    '.....ee.EE......',
  ],
  surgeon: [
    '......wwwwE.....',
    '.......wE.......',
    '......EeeE......',
    '......cbcb......',
    '......EeeE......',
    '.......gE.......',
    '.....eeeeE......',
    '....eEeeeEE.....',
    '....e.EeeE.g....',
    '....e.eeeE.g....',
    '....E.EeE..g....',
    '....e.eEeE.g....',
    '...Eg.e..E.g....',
    '......e..E.g....',
    '......E..E.g....',
    '.....gg..gg.c...',
  ],
  surgeonB: [ // idle: probe raised, lens array lit
    '......wwwwE..c..',
    '.......wE....g..',
    '......EeeE...g..',
    '......cwcw...g..',
    '......EeeE...g..',
    '.......gE....g..',
    '.....eeeeE..g...',
    '....eEeeeEEg....',
    '....e.EeeE......',
    '....e.eeeE......',
    '....E.EeE.......',
    '....e.eEeE......',
    '...Eg.e..E......',
    '......e..E......',
    '......E..E......',
    '.....gg..gg.....',
  ],
  choir: [
    '................',
    '......TgT.......',
    '..TgT.GpG.TgT...',
    '..GpGGTZTGGpG...',
    '..TGT..Z..TGT...',
    '...TgT.G.TgT....',
    '...GpGGZGGpG....',
    '...TGT.Z.TGT....',
    '.......G..TgT...',
    '..TgT.GZGGGpG...',
    '..GpGGZG..TGT...',
    '..TGT..Z........',
    '.......G........',
    '......T.T.......',
    '.....T...T......',
    '................',
  ],
  choirB: [ // idle: the speaker heads pulse
    '................',
    '......TgT.......',
    '..TgT.GPG.TgT...',
    '..GwGGTZTGGPG...',
    '..TGT..Z..TGT...',
    '...TgT.G.TgT....',
    '...GPGGZGGwG....',
    '...TGT.Z.TGT....',
    '.......G..TgT...',
    '..TgT.GZGGGwG...',
    '..GPGGZG..TGT...',
    '..TGT..Z........',
    '.......G........',
    '.......TT.......',
    '......T..T......',
    '................',
  ],
  knight: [
    '................',
    '......GZZG......',
    '.....GZgZZG.....',
    '.....ZrrrZZ.....',
    '......TZZT......',
    '...GZZGZZGZZG...',
    '..GZGZZZZZZGZG..',
    '.qqqqZGZZGZZGZ..',
    '.qQQqTZGGZTZ.g..',
    '.qrrqTZZZZT..g..',
    '.qQQqTGZZGT..g..',
    '.qQQqTZTTZT..r..',
    '.qqqq.ZT.ZT.....',
    '......GT.GT.....',
    '......ZT.ZT.....',
    '.....ZZT.TZZ....',
  ],
  knightL: [ // idle: visor glances left
    '................',
    '......GZZG......',
    '.....GZgZZG.....',
    '.....rrrZZZ.....',
    '......TZZT......',
    '...GZZGZZGZZG...',
    '..GZGZZZZZZGZG..',
    '.qqqqZGZZGZZGZ..',
    '.qQQqTZGGZTZ.g..',
    '.qrrqTZZZZT..g..',
    '.qQQqTGZZGT..g..',
    '.qQQqTZTTZT..r..',
    '.qqqq.ZT.ZT.....',
    '......GT.GT.....',
    '......ZT.ZT.....',
    '.....ZZT.TZZ....',
  ],
  warden: [
    '....TTZZZZTT....',
    '..TTZGZGGZGZTT..',
    '.TZGZThhhhTZGZT.',
    '.ZGZThwwwwhTZGZ.',
    '.ZZTGwwwwwwGTZZ.',
    '.ZGTGwhwwhwGTGZ.',
    '.ZZThwwwwwehTZZ.',
    '.ZGThhwwwehhTGZ.',
    '.ZZThhhwehhhTZZ.',
    '.CGZhGZeeZGhZGC.',
    'TCZhGZzZZzZGhZCT',
    'TCTeZzzZZzzZeTCT',
    'TCTTZhzZZzhZTTCT',
    'TCThhzZhhZzhhTCT',
    'TTTTTTTTTTTTTTTT',
    'TZTZTZTZTZTZTZTZ',
  ],
  wardenE: [ // idle: eyes lit
    '....TTZZZZTT....',
    '..TTZGZGGZGZTT..',
    '.TZGZThhhhTZGZT.',
    '.ZGZThwwwwhTZGZ.',
    '.ZZTGwwwwwwGTZZ.',
    '.ZGTGwrwwrwGTGZ.',
    '.ZZThwwwwwehTZZ.',
    '.ZGThhwwwehhTGZ.',
    '.ZZThhhwehhhTZZ.',
    '.CGZhGZeeZGhZGC.',
    'TCZhGZzZZzZGhZCT',
    'TCTeZzzZZzzZeTCT',
    'TCTTZhzZZzhZTTCT',
    'TCThhzZhhZzhhTCT',
    'TTTTTTTTTTTTTTTT',
    'TZTZTZTZTZTZTZTZ',
  ],
  // NPCs, also used as 16x16 dialog portraits. Adult or mechanical proportions, one accent each.
  // The Archivist: an engineer's ghost in a long coat, stooped, head bowed over cupped hands that hold nothing.
  archivist: [
    '................',
    '................',
    '......AAA.......',
    '.....AAAAe......',
    '.....AAAee......',
    '.....a.AeE......',
    '....aaa.E.......',
    '...eaaaa........',
    '...eaAaaaee.....',
    '...eaAav.eEe....',
    '...eaAaa........',
    '...eaaAa........',
    '...eAaAa........',
    '...a.aAaa.......',
    '...a.A.A........',
    '.....a..a.......',
  ],
  // LAMBDA in a shard of the cracked visor: a tall stylus-drawn figure, scanline hair, the two strokes of the glyph for legs,
  // and a face the girl never finished (one eye drawn, the glass shows through the rest). Dialog portrait only.
  lambda: [
    '...dddddddd.....',
    '..dddddCCCddC...',
    '.dddddcccccd.C..',
    '.ddddCCwddCC....',
    'dddddccdd.ccdd..',
    '.ddddcddcddc.dC.',
    '.ddddCcccccC.dd.',
    'dddddcdCcCdcddd.',
    '.ddddCdCwCdCdddd',
    '.ddddcdCcCdcddd.',
    '..dddddCcCddddd.',
    '.dddddddccdddddd',
    '.Cddddddcdcdddd.',
    '..C.dddcddcddd..',
    '..dddddcdddcddd.',
    '...dddcddddcd...',
  ],
  // LAMBDA from 81F: pixels missing, scanlines torn sideways.
  lambdaFade: [
    '...dddddddd.....',
    '..dddddCCCddC...',
    '.dddddcCdcdd.C..',
    '.dddddCwcddCC...',
    'ddddddCddddcCd..',
    '.ddddcddcddd.dC.',
    '.dddddCccCcC.dd.',
    'ddddCdCCCdCdddd.',
    '.ddddCdCcCdddddd',
    '.ddddddcddcCdcd.',
    '..dddddCCdddddd.',
    '.dddddddccdddddd',
    '.Cdddddcdcddddd.',
    '..C.dddcdddddd..',
    '..dddddddddcddd.',
    '...dddCdddddd...',
  ],
  // LAMBDA from 95F: only the two walking strokes of the glyph remain, faint.
  lambdaGlyph: [
    '...dddddddd.....',
    '..ddddddddddC...',
    '.ddddddddddd.C..',
    '.ddddddcdddd....',
    'dddddddCddd.dd..',
    '.dddddddCddd.dC.',
    '.dddddddcddd.dd.',
    'ddddddddCdddddd.',
    '.ddddddddCdddddd',
    '.ddddddddCddddd.',
    '..dddddddCddddd.',
    '.dddddddCddddddd',
    '.CddddddCdcdddd.',
    '..C.dddCddCddd..',
    '..dddddCdddCddd.',
    '...dddcddddcd...',
  ],
  // Brann: a big loud man in a work coat, beard, hard hat with a headlamp, rock drill in hand.
  brann: [
    '................',
    '.....NNNNN......',
    '....NNNNNNOy....',
    '....NSSsssS.....',
    '....NshsshS.....',
    '....NNNsNNN.....',
    '...nnNNhNNNn....',
    '..nnnnNNNnnnn...',
    '.nnNnnnNnnnNnn..',
    '.nn.nnnnnnnGGGg.',
    '.nn.NNYNNNsGgGgw',
    '.ss.nnnnnnsGGG..',
    '....nnnnnnn.....',
    '....NnN..NnN....',
    '....NNN..NNN....',
    '...NNNN..NNNN...',
  ],
  // Sister Ohm: a tall nursery carrier unit, head tilted, candles burning in her open chest cavity.
  ohm: [
    '........qq......',
    '.......qqqQ.....',
    '.......QhhQ.....',
    '........QQ......',
    '........Q.......',
    '.....qqqqqqq....',
    '....QqqqqqqqQ...',
    '...Qq.hYYh.qQ...',
    '...qQ.YYOY.Qq...',
    '...qQ.OYlY.Qq...',
    '...qQ.lYlO.Qq...',
    '...qQ.hlll.Qq...',
    '...Q..QqqQ..Q...',
    '....qQ.QQ.Qq....',
    '......Q..Q......',
    '.....QQ..QQ.....',
  ],
  // Pip: a small nursery speaker unit on thin legs, antenna up, listening for its mother.
  pip: [
    '................',
    '................',
    '................',
    '...........c....',
    '..........g.....',
    '..........g.....',
    '......GGGGGG....',
    '.....GhhhhhG....',
    '.....GggggGGc...',
    '.....GhhhhhG....',
    '......ZGGGZ.....',
    '.......g.g......',
    '......g...g.....',
    '.......g...g....',
    '......g...g.....',
    '.....gg...gg....',
  ],
  // The Broker: hunched under a tarp, one lens peering through a slit, many thin hands out with goods.
  broker: [
    '................',
    '................',
    '.......TT.......',
    '......TZZT......',
    '.....TZZZZT.....',
    '....TZZhZZZT....',
    '...TZZZhyZZZT...',
    '...TZZZhZZZZT...',
    '..TZZZZZZZZZZT..',
    'ggTZZTZUUTZZTgg.',
    'q.gTZTZZZTZTgq..',
    '.yYTZTZZZTZTgg.q',
    '..gTZTZZZTZZTg..',
    '...TZTZZZTZZT...',
    '..TTZTTZZTTZTT..',
    '...g.g....g.g...',
  ],
  // The Stranger: tall and ragged, long grey hair hanging over the face. Never clearly anyone.
  wanderer: [
    '................',
    '.......ggg......',
    '......ggggg.....',
    '......gGgGg.....',
    '......gGgGg.....',
    '......gGsGg.....',
    '.....QgGgGgQ....',
    '....QQAgGgAQQ...',
    '....QAAgAgAAQ...',
    '...QAAQAAAQAAQ..',
    '...sAAQAAAQAAs..',
    '....AAQAAAQAA...',
    '....QAQAAAQAQ...',
    '....A.QAAAQ.A...',
    '......Q.A.Q.....',
    '......QQ..QQ....',
  ],
  // T., the Tallyman: a stout surveyor in a bulbous pressure rig, round helmet port, tally marks, a clicker counter.
  tallyman: [
    '................',
    '......YYYY......',
    '.....YEeeEY.....',
    '....YESsssEY....',
    '....YEshshEY....',
    '....YENNNsEY....',
    '..GuuYEEEEYuuG..',
    '.GuuuuYYYYuuuuG.',
    '.GuhuhuhUuuuuuG.',
    '.GuhuhuhUuuuuuGg',
    '.Gu.uuuuuuuu.GrG',
    '.uG.UuuuuuuU.Ggg',
    '....UuuuuuuU....',
    '....UuuU.UuuU...',
    '....GGG...GGG...',
    '...GGGG...GGGG..',
  ],
  // The Tallyman's copy from the Silent Stratum: the same rig, perfect, clean and pale, a red LED where his face was.
  tallymanCopy: [
    '................',
    '......gggg......',
    '.....ghhhhg.....',
    '....ghhhhhhg....',
    '....ghhrrhhg....',
    '....ghhhhhhg....',
    '..ewwghhhhgwwe..',
    '.ewwwwggggwwwwe.',
    '.ewwwwwwwwwwwwe.',
    '.ewwwwwwwwwwwweg',
    '.ew.wwwwwwww.egg',
    '.we.ewwwwwwe.egg',
    '....ewwwwwwe....',
    '....ewwe.ewwe...',
    '....ggg...ggg...',
    '...gggg...gggg..',
  ],
  // Verity: a debugger AI in a scavenged maintenance frame, headset and mic, a probe cable still plugged into nothing.
  verity: [
    '................',
    '......gggg......',
    '.....g.ZZ.g.....',
    '....GGZZZZGG....',
    '....GGhvhZGGZ...',
    '.....gZZZZ..Z...',
    '......vZZ...Z...',
    '.......Z....Z...',
    '......GZZG..Z...',
    '.....G.ZZ.G.Zg..',
    '.....Z.ZZ.Z..gv.',
    '.....G..Z..G....',
    '......GZZG......',
    '.....GZ..ZG.....',
    '......Z..Z......',
    '.....GG..GG.....',
  ],
  // Map tiles and items: bold, flat silhouettes. HP = green cells, ATK = red, DEF = blue.
  fabricator: [
    '................',
    '..GGGGGGGGGGGG..',
    '..GgvgvggggggG..',
    '..GGGGGGGGGGGG..',
    '..GzzzzqqzzzzG..',
    '..GzzzzzzzzzzG..',
    '..GzzzOooOzzzG..',
    '..GzzzoooozzzG..',
    '..GzzQQQQQQzzG..',
    '..GGGGGGGGGGGG..',
    '..GggggggggggG..',
    '..GgkkkkkkkkgG..',
    '..GggggggggggG..',
    '..GGGGGGGGGGGG..',
    '..GG........GG..',
  ],
  root: [
    '.....GGGGGG.....',
    '....GzzzzzzG....',
    '....GzcccczG....',
    '....GzcwwczG....',
    '....GzcwwczG....',
    '....GzcccczG....',
    '....GzzzzzzG....',
    '....GzvzzvzG....',
    '....GzzzzzzG....',
    '....GzvzzvzG....',
    '....GzzzzzzG....',
    '...GGGGGGGGGG...',
    '..GggggggggggG..',
    '..GGGGGGGGGGGG..',
  ],
  cardY: [
    '................', '................', '................', '................',
    '..yyyy..........',
    '.ywwyyy.........',
    '.yw..yyyyyyyyyy.',
    '.yy..yyYYYYYYYY.',
    '.yyyyyY...YY.YY.',
    '..YYYY....YY..Y.',
  ],
  doorY: [
    'zzzzzzzzzzzzzzzz',
    'zGGGGGGGGGGGGGGz',
    'zyyyyyyyyyyyyyyz',
    'zYYYYkkkkkkYYYYz',
    'zyyyykqqqqkyyyyz',
    'zYYYYkqkkqkYYYYz',
    'zyyykkqkkqkkyyyz',
    'zYYYkwwwwwwkYYYz',
    'zyyykwwkkwwkyyyz',
    'zYYYkwwkkwwkYYYz',
    'zyyykqqqqqqkyyyz',
    'zYYYkkkkkkkkYYYz',
    'zyyyyyyyyyyyyyyz',
    'zYYYYYYYYYYYYYYz',
    'zGGGGGGGGGGGGGGz',
    'zzzzzzzzzzzzzzzz',
  ],
  battery: [
    '................', '................',
    '......qqqq......',
    '....GGGGGGGG....',
    '....vvvvvvvV....',
    '....vvvwwvvV....',
    '....vvvwwvvV....',
    '....vwwwwwwV....',
    '....vwwwwwwV....',
    '....vvvwwvvV....',
    '....vvvwwvvV....',
    '....vvvvvvvV....',
    '....VVVVVVVV....',
    '....GGGGGGGG....',
  ],
  supercap: [
    '................',
    '.....q....q.....',
    '.....q....q.....',
    '..GGGGGGGGGGGG..',
    '..qqqqqqqqqqqG..',
    '..vvvvvvvvvvvV..',
    '..vvvvvwwvvvvV..',
    '..vvvvvwwvvvvV..',
    '..vvvwwwwwwvvV..',
    '..vvvwwwwwwvvV..',
    '..vvvvvwwvvvvV..',
    '..vvvvvwwvvvvV..',
    '..vvvvvvvvvvvV..',
    '..VVVVVVVVVVVV..',
    '..GGGGGGGGGGGG..',
  ],
  ram: [
    '................', '................', '................',
    '.bbbbbbbbbbbbbb.',
    '.bwbbbbbbbbbbbB.',
    '.bzzzbzzzbzzzbB.',
    '.bzzzbzzzbzzzbB.',
    '.bzzzbzzzbzzzbB.',
    '.bbbbbbbbbbbbbB.',
    '.BBBBBBBBBBBBBB.',
    '..y.y.y..y.y.y..',
    '..y.y.y..y.y.y..',
  ],
  chipA: [
    '................', '................',
    '....q.q..q.q....',
    '...rrrrrrrrrr...',
    '..qrwrrrrrrrRq..',
    '...rrrrrrrrrR...',
    '..qrrrRRRRrrRq..',
    '...rrrRwwRrrR...',
    '...rrrRwwRrrR...',
    '..qrrrRRRRrrRq..',
    '...rrrrrrrrrR...',
    '..qrrrrrrrrrRq..',
    '...RRRRRRRRRR...',
    '....q.q..q.q....',
  ],
  lance: [
    '................',
    '.............cc.',
    '............cwc.',
    '...........cwc..',
    '..........cwc...',
    '.........cwc....',
    '....gG..cwc.....',
    '.....gGcwc......',
    '......gGG.......',
    '.....QQgG.......',
    '....QQ..gG......',
    '...QQ...........',
    '..GG............',
    '..G.............',
  ],
  lattice: [
    '................', '................',
    '...gggggggggg...',
    '...geeeccEEEG...',
    '...geeeccEEEG...',
    '...gccccccccG...',
    '...geeeccEEEG...',
    '...geeeccEEEG...',
    '...geeeccEEEG...',
    '...geeeccEEEG...',
    '....geeccEEG....',
    '.....geccEG.....',
    '......gcCG......',
    '.......GG.......',
  ],
  floppy: [
    '................', '................',
    '..ZZZZZZZZZZZ...',
    '..ZZqqqqqGqZZZ..',
    '..ZZqqqqqGqZZZ..',
    '..ZZqqqqqqqZZZ..',
    '..ZZZZZZZZZZZZ..',
    '..ZwwwwwwwwwwZ..',
    '..ZwwwwvvwwwwZ..',
    '..ZwwwvvvvwwwZ..',
    '..ZwwwvvvvwwwZ..',
    '..ZwwwwvvwwwwZ..',
    '..ZwwwwwwwwwwZ..',
    '..ZZZZZZZZZZZZ..',
  ],
  compass: [
    '................', '................',
    '.....qqqqqq.....',
    '....qzzzzzzq....',
    '...qzzzrrzzzq...',
    '..qzzzzrrzzzzq..',
    '..qzzzrrrrzzzq..',
    '..qzzzrrrrzzzq..',
    '..qzzzwwwwzzzq..',
    '..qzzzwwwwzzzq..',
    '..qzzzzwwzzzzq..',
    '...qzzzwwzzzq...',
    '....qzzzzzzq....',
    '.....qqqqqq.....',
  ],
  shard: [
    '................',
    '.......Oy.......',
    '......OOyy......',
    '.....OOyyYY.....',
    '.....OOyyYY.....',
    '.....OOyyYY.....',
    '.....OOyyYY.....',
    '.....OOyyYY.....',
    '.....OOyyYY.....',
    '.....OOyyYY.....',
    '......OyyY......',
    '.......yY.......',
  ],
  note: [
    '................', '................', '................', '................',
    '....llllllll....',
    '....lnnnnnlll...',
    '....lllllllll...',
    '....lnnnnnnnl...',
    '....lllllllll...',
    '....lnnnnlllS...',
    '....llllllllS...',
    '....SSSSSSSSS...',
  ],
  credit: [
    '................', '................', '................',
    '.....yyyyyy.....',
    '....yOOyyyyY....',
    '...yOyyYYYyyY...',
    '...yOyYyyyyyY...',
    '...yyyYyyyyyY...',
    '...yyyYyyyyyY...',
    '...yyyyYYYyyY...',
    '....yyyyyyyY....',
    '.....YYYYYY.....',
  ],
};

// Named palette swaps: [base sprite, {from: to}]. Monster rosters add their own swaps in world.js.
const VARIANTS = {
  cardB: ['cardY', { y: 'b', Y: 'B' }],
  cardR: ['cardY', { y: 'r', Y: 'R' }],
  doorB: ['doorY', { y: 'b', Y: 'B' }],
  doorR: ['doorY', { y: 'r', Y: 'R' }],
  chipD: ['chipA', { r: 'b', R: 'B' }],
  rootDark: ['root', { c: 'T', w: 't', v: 'Z' }],
  serverDead: ['root', { c: 'Z', w: 'T', v: 'z' }],
  drill: ['lance', { G: 'N', g: 'n', c: 'y', Q: 'N' }],
};

// Map tile -> item kind. Values scale by zone (see BALANCE in balance.js).
const ITEMS = {
  y: { kind: 'key', key: 'y', name: 'Amber Keycard', sprite: 'cardY' },
  b: { kind: 'key', key: 'b', name: 'Cyan Keycard', sprite: 'cardB' },
  r: { kind: 'key', key: 'r', name: 'Crimson Keycard', sprite: 'cardR' },
  h: { kind: 'hp', name: 'Li-ion Cell', sprite: 'battery' },
  H: { kind: 'hp', name: 'Supercapacitor', sprite: 'supercap' },
  a: { kind: 'atk', name: 'CPU Core', sprite: 'chipA' },
  d: { kind: 'def', name: 'ECC RAM', sprite: 'ram' },
  w: { kind: 'atk', gear: true, sprite: 'lance' },
  e: { kind: 'def', gear: true, sprite: 'lattice' },
  v: { kind: 'antivirus', name: 'Antivirus Disk', sprite: 'floppy' },
  c: { kind: 'compass', name: 'Phase Compass', sprite: 'compass' },
  '*': { kind: 'shard', name: 'Memory Shard', sprite: 'shard' },
};

const DOORS = { Y: 'y', B: 'b', R: 'r' };
const KEY_NAMES = { y: 'Amber', b: 'Cyan', r: 'Crimson' };

const ABILITIES = {
  swift: 'Swift: strikes first',
  double: 'Twin: attacks twice',
  pierce: 'Pierce: ignores DEF',
  corrupt: 'Corrupt: infects on contact',
  aura: 'Field: hurts when adjacent',
  surge: 'Overflow: every 3rd blow x2',
};

// CRIT = % chance of a x2 hit. Each point of AGI above the attacker's adds 3% dodge.
const hitChances = (atk, def) => ({ crit: atk.crit / 100, miss: Math.min(0.4, Math.max(0.02, 0.04 + 0.03 * (def.agi - atk.agi))) });

// Expected HP lost fighting monster m, averaging in both sides' misses and crits.
// Infinity if the hero can't hurt it.
function battleCost(hero, m) {
  const hd = hero.atk - m.def;
  if (hd <= 0) return Infinity;
  const mine = hitChances(hero, m), theirs = hitChances(m, hero);
  const swings = Math.max(1, Math.ceil(m.hp / (hd * (1 - mine.miss) * (1 + mine.crit))));
  let hits = (swings - 1 + (m.swift ? 1 : 0)) * (m.double ? 2 : 1);
  if (m.surge) hits += Math.floor(hits / 3);
  const dmg = m.pierce ? m.atk : Math.max(0, m.atk - hero.def);
  return Math.round(hits * dmg * (1 - theirs.miss) * (1 + theirs.crit));
}

const HERO_START = { hp: 1000, atk: 10, def: 10, crit: 5, agi: 2, gold: 0, exp: 0, lv: 1, keys: { y: 1, b: 0, r: 0 } };
const expToNext = lv => 5 * lv * (lv + 1); // cumulative: 10, 30, 60, 100...
const levelGain = (lv, h) => ({ hp: Math.round(h.hp * 0.04 + 50), atk: Math.max(1, Math.round(h.atk * 0.02)), def: Math.max(1, Math.round(h.def * 0.02)), agi: lv % 3 === 0 ? 1 : 0 });
const fabricatorCost = n => 20 + 10 * n + 2 * n * n;

// Zone monsters and bosses (rosters in world.js ZONES). Kept apart from the base sprites above.
Object.assign(SPRITES, {
  // -- Cable Nave
  leech: [
    '................',
    '................',
    '................',
    '.........TZZZT..',
    '........TGgGgGT.',
    '........gZhhhZg.',
    '........GhhhhhG.',
    '........gZhhvZg.',
    '........TGgGgGT.',
    '.........TZGZ...',
    '...TZGZgZGZgZ...',
    '..ZgZGZgZGZgZT..',
    '.ZgZGZgZGZgZT...',
    '.TZTZTZTZTZT....',
    '................',
    '................',
  ],
  tangle: [
    '................',
    '.g..........g...',
    '..g........g....',
    '..GZ.GGGG.ZG....',
    '...ZGZZZZGZ.....',
    '..GZT...TVv.....',
    '.GZ..GGVvZG.....',
    '.GZ.GZVTTGZ.....',
    '.GZ.ZvT..GZ.....',
    '.TZG.ZT.GZT.GG..',
    '..TZGGZGZT.GZ.g.',
    '...TZZTZGGGZT...',
    '....G..TZZT.....',
    '...gG...........',
    '..g.............',
    '................',
  ],
  motherworm: [
    '...TZZZZT.......',
    '..ZGvGGvGZTZZT..',
    '.ZvTthhtTvZGGZT.',
    '.ZGthhhhtGZZZGGZ',
    '.ZvTthhtTvZ..TGZ',
    '..ZGvGGvGZ....ZG',
    '..TZGGZT......ZG',
    '.TZGZ....TZT..ZG',
    '.ZGZ.....GvG.TZG',
    '.ZGZ......T..ZGZ',
    '.ZGZT.......TZGZ',
    '.TZGZT....TZGZT.',
    '..TZGGZZZZGGZT..',
    '...TZZGGGGZZT...',
    '..TZT..TZT......',
    '..GvG..GvG......',
  ],
  // -- Dead Concrete boss
  janitor: [
    '.....TZZZT......',
    '....TZGggZT.....',
    '....ZGT..TZT....',
    '....ZG....TZT...',
    '....ZG....ZyOZ..',
    '...TZZT....ZZ...',
    '..gZGgZg........',
    '..GZGGZ.GG......',
    '..GTZZT..GG.....',
    '.G..ZG....GZZZT.',
    '.G..ZG....ZGggZ.',
    'G...ZZ....ZGGGZ.',
    'G..TZTZ...ZGTGZ.',
    'cG.G...G..ZGGGZ.',
    'OcOG...G..TZZZT.',
    'c.cG...GG..h.h..',
  ],
  // -- Silicate Wards
  drip: [
    '..gGGGGGGGGg....',
    '..g....G...g....',
    '.eEEe..G..eEe...',
    '.ewwE..G..ecE...',
    '.eccE..G..ecE...',
    '.eccE..G...C....',
    '.eCcE..G...c....',
    '..eE...G...c....',
    '...c..gGg..c....',
    '...c.g.G.g.c....',
    '...cg..G..gc....',
    '...w...G...w....',
    '.......G........',
    '.....TZZZT......',
    '....G.G.G.G.....',
    '...hG.h.h.Gh....',
  ],
  patient: [
    '...G........G...',
    '...GTZZZZZZTG...',
    '...G..eEe...G.c.',
    '...G.ecbce..GcC.',
    '...G..eEe...C...',
    '...ZZZZeZZZZZ...',
    '...GewweweEEG...',
    '.c.Ge.eweE.EG...',
    'cCcGe.ewwE.EG...',
    '.C.ZZZZZZZZZZ...',
    '...G..eE.eE.G...',
    '...G..eE.eE.G...',
    '...ZZZZZZZZZZ...',
    '...G..E...E.G...',
    '..G.G......G.G..',
    '.GG..G....G..GG.',
  ],
  syringe: [
    '................',
    '................',
    '................',
    '....ggg...ggg...',
    '.....G.....G....',
    '.....GZZZZZG....',
    '...eEEEEEEEEE.G.',
    'w..ecCcccccCeGGG',
    'wgGEcccccccceGgG',
    'w..ecCcccCccEGGG',
    '...eEEEEEEEEE.G.',
    '....G.G.G.G.....',
    '................',
    '................',
    '................',
    '................',
  ],
  surgeonBoss: [
    'TZZZZZZZZZZZZZZT',
    '.......ZG.......',
    '.......ZG.......',
    '.....TZGGZT.....',
    '....ZOOOOOOZ....',
    '....TwwwwwwT....',
    '.g...TZGGZT...w.',
    '..G.ZGZGGZGZ.G..',
    '...GZ.ZGGZ.ZG...',
    '.w..G.ZGGZ.G..G.',
    'G..G..TZZT..G..g',
    '..G...G..G...G..',
    '.G...G....G...c.',
    '.w...g....G.....',
    '....gGg...c.....',
    '.....g..........',
  ],
  // -- The Foundry
  slag: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....TTT..TT....',
    '...TTZZZTTZZTT..',
    '..TZZZZNoZZZZZT.',
    '..ZZZNoZZyNZZZT.',
    '.TZNoZZZZZoNZZZ.',
    '.ZZZZZTZZZZZZGr.',
    '.TGgGGGGGGGGgGG.',
    '..G.TG..GT..G.G.',
    '.g..g..g..g..g..',
    '................',
  ],
  crab: [
    '................',
    '.TZZZT....TZZZT.',
    '.ZGgGZ....ZGgGZ.',
    '.TZZZT....TZZZT.',
    '.gG..Z....Z..Gg.',
    '.o...Z....Z...o.',
    '....Z......Z....',
    '...TZZZZZZZZT...',
    '..TZGgGgGgGGZT..',
    '..ZGGGGGGGGGGZ..',
    '..TZZZZZZZZrZT..',
    '...G.G.TT.G.G...',
    '..G..G.TT.G..G..',
    '..G.G..G.G..G.G.',
    '.g..g..g..g..g..',
    '................',
  ],
  furnace: [
    '................',
    '..........Z.....',
    '....TTTTTTZT....',
    '...TZZZZZZZZT...',
    '...ZGgGGGGgGZ...',
    '...ZGhhhhhhGZ...',
    '...ZGohyhohGZ...',
    '...ZGyhOhyhGZ...',
    '...ZGohyhohGZ...',
    '...ZGhhhhhhGZ...',
    '...ZGGGGGGGGZ...',
    '...TZZTTTTZZT...',
    '....ZG....GZ....',
    '....g......g....',
    '...Tg......gT...',
    '...ZZ......ZZ...',
  ],
  masonII: [
    '................',
    '......TZZT......',
    '......ZGrZ......',
    '..TTTTTZZTTTTT..',
    '.TZZGGGGGGGGZZT.',
    '.ZGGoGGGGGGoGGZ.',
    '.ZGGGSssssSGGGZ.',
    '.ZhGGsTssTsGGhZ.',
    '.ZoGGssssSsGGoZ.',
    '.ZhGGsSSSssGGhZ.',
    '.ZGGoGssssGoGGZ.',
    '.gZTTZZZZZZTTZg.',
    '.o..ZGG..GGZ.gg.',
    '....ZGG..GGZ....',
    '...TZZZ..ZZZT...',
    '...hhhh..hhhh...',
  ],
  crane: [
    '................',
    '..TTTTTTTTTTTTT.',
    '..ZoZoZoZoZoZGZ.',
    '..TZGZTTTTTTTgT.',
    '...ZGZ.......g..',
    '..TZrZT......g..',
    '..ZGGGZ.....TgT.',
    '..TZGZT.....g.g.',
    '...ZGZ......ZZ..',
    '...ZGZ.....GTTG.',
    '..TZ.ZT...G.G.G.',
    '..Z...Z...g.T.g.',
    '.TZ...ZT...TGT..',
    '.Z.....Z...G.G..',
    '.Z.....Z...G.T..',
    '.hh...hh........',
  ],
  foreman: [
    '................',
    '......yy........',
    '.....TooT.......',
    '....EEEEEE......',
    '...EeTTTTeE.....',
    '...ETZrZZTE.....',
    '...ETZZZZTE...T.',
    '..TEEEEEEEET.TZ.',
    '.TZGGGGGGGZTZZg.',
    '.ZGgGGGGgGZZZGg.',
    '.ZGGGGGGGGZ..TZ.',
    '.TTTTTTTTTTT..T.',
    '.ZyhyhyhyhyZ....',
    '.ZGGGGGGGGGZ....',
    '.ZGGGGGGGGGZ....',
    '.TTTTTTTTTTT....',
  ],
  // -- Drowned Archive
  crawler: [
    '................',
    '................',
    '................',
    '..G..........G..',
    '..GG........GG..',
    '.G..G......G..G.',
    '.G.G.GTZZTG.G.G.',
    '.G.G.ZGggGZ.G.G.',
    '.G.GGZGGGGZGG.G.',
    '.G..TZcCcCZT..G.',
    '.G..G.TZZT.G..G.',
    '.g.G...CC...G.g.',
    '...G........G...',
    '..g..........g..',
    '................',
    '................',
  ],
  crawlerB: [ // idle: legs shift, the scanner sweeps
    '................',
    '................',
    '................',
    '................',
    '..GG........GG..',
    '.G..G......G..G.',
    '.G..GGTZZTGG..G.',
    '.G.G.ZGggGZ.G.G.',
    '.G.GGZGGGGZGG.G.',
    '.g..TZCcCcZT..g.',
    '..G.G.TZZT.G.G..',
    '..G.G...CC.G.G..',
    '..g..G.....G..g.',
    '.....g.....g....',
    '................',
    '................',
  ],
  bitrot: [
    '................',
    '.........TZZZT..',
    '........TZGgGZT.',
    '........ZGhcGGZ.',
    '.......TZGGBGZT.',
    '.....TTZBBZZT...',
    '...TZZBGBZT.....',
    '..TZGB.GZT......',
    '..ZGBAZBT.......',
    '..TZGBGZZT......',
    '...TZB.GBZZT....',
    '....TTZGBABZT...',
    '......TZBZ.BZ...',
    '........T.Z..B..',
    '..........T.B...',
    '...........T..B.',
  ],
  drowned: [
    '................',
    '.....TZZZZT.....',
    '....TZGgGGZT....',
    '....ZGhhhhGZCC..',
    '....ZGhhhOGZ.C..',
    '....ZGhhhhGZ.c..',
    '...TTZGGGGZTTC..',
    '..TZBBZZZZBBZC..',
    '.TZBBBBGBBBBBZ..',
    '.ZBZBBBGBBBBZBZ.',
    '.ZB.ZBBBBBBZ.BZ.',
    '.Gg.ZBBTTBBZ.gG.',
    '.g..ZBB..BBZ..g.',
    '....ZBB..BBZ....',
    '...TZZZ..ZZZT...',
    '...hhhh..hhhh...',
  ],
  pages: [
    '................',
    '.......qq.......',
    '..qq...qT.......',
    '.qTq...qq...qq..',
    '..qQ.......qTqq.',
    '............qQ..',
    '......TZZT......',
    '.qq..TZcCZT..qq.',
    '.qTq..TZZT..qTq.',
    '.qqQ...GG...qQq.',
    '................',
    '..qq.......qq...',
    '.qTqq.....qTq...',
    '..qQ...qq..qQ...',
    '.......qT.......',
    '.......qQ.......',
  ],
  pagesB: [ // idle: the pages turn around the core
    '................',
    '....qq.....qq...',
    '...qTq....qTq...',
    '...qQ......qQ...',
    '................',
    '..qq............',
    '.qTq..TZZT...q..',
    '..qQ.TZCcZT.qTq.',
    '......TZZT..qqQ.',
    '..q....GG.......',
    '.qTq............',
    '..qQ........qq..',
    '...........qTq..',
    '.....qq....qQ...',
    '....qTqq........',
    '.....qQ.........',
  ],
  angler: [
    '................',
    '.........TZZT...',
    '........TZGgZT..',
    '.......TZGT.TGZ.',
    '.......ZGT..ZGT.',
    '......TgZ...TcT.',
    '......ZGT....c..',
    '......ZG........',
    '.......ZG.......',
    '.......ZG.......',
    '.......ZG.......',
    '......TZGT......',
    '.....TZGgZT.....',
    '...TZZZZZZZZT...',
    '..TZGgGGGGgGZT..',
    '...TTTTTTTTTT...',
  ],
  anglerL: [ // idle: the arm sweeps aside
    '................',
    '................',
    '..TZZZT.........',
    '.TZGgGZZT.......',
    '.ZGT..TZGZT.....',
    '.TcT....TZGT....',
    '..c.......ZGT...',
    '...........ZG...',
    '..........ZG....',
    '.........ZG.....',
    '........ZG......',
    '.......TZGT.....',
    '.....TZGgZT.....',
    '...TZZZZZZZZT...',
    '..TZGgGGGGgGZT..',
    '...TTTTTTTTTT...',
  ],
  librarian: [
    '................',
    '.....TT.........',
    '....TZGT........',
    '...TZGGZ........',
    '..OcTTZ.........',
    '......TZ........',
    '....TZZZZZZT....',
    '...GZBEbCBeZG...',
    '...GZBEbCBeZG...',
    '...gZGGGGGGZg...',
    '...gZbT.BEBZg...',
    '...GZbTcBEBZG...',
    '...GZGGGGGGZG...',
    '...gTZZZZZZTg...',
    '..g..ZG..GZ..g..',
    '.....ZG..GZ.....',
  ],
  // -- Choir of Static
  seraph: [
    '................',
    '..p..........p..',
    '...G...pp...G...',
    '.p..G.TGGT.G..p.',
    '..G..ZG..GZ..G..',
    '...GZ.w....ZG...',
    '....Z..p...Z....',
    '.pGGZ..w...ZGGp.',
    '....Z...w..Z....',
    '...GZ....p.ZG...',
    '..G..ZG..GZ..G..',
    '.p....TGGT....p.',
    '.......pp.......',
    '................',
    '................',
    '................',
  ],
  feedback: [
    '................',
    '................',
    '..........Tg....',
    '..........ZGT...',
    '.......pp.gGZT..',
    '......w..pgGGZ..',
    '...TgTgp.pgGGZT.',
    '.TZZTgT..pgGGZT.',
    '.TZZgTgp.pgGGZT.',
    '...TTgTp.wgGGZT.',
    '......p..pgGGZ..',
    '.......pw.gGZT..',
    '..........ZGT...',
    '..........Tg....',
    '................',
    '................',
  ],
  feedbackB: [ // idle: the loop crackles
    '................',
    '................',
    '..........Tg....',
    '.......w..ZGT...',
    '.......pw.gGZT..',
    '......p..pgGGZ..',
    '...TgTgw.pgGGZT.',
    '.TZZTgTp.wgGGZT.',
    '.TZZgTgp.pgGGZT.',
    '...TTgTp.pgGGZT.',
    '......w..pgGGZ..',
    '.......pp.gGZT..',
    '..........ZGTw..',
    '..........Tg....',
    '................',
    '................',
  ],
  speaker: [
    '................',
    '..TTTTTTTTTTTT..',
    '..ZPPPPPPPPPPZ..',
    '..ZPTTttttTTPZ..',
    '..ZPTtZGZttTPZ..',
    '..ZPTthGhttTPZ..',
    '..ZPTtZGZttTPZ..',
    '..ZPTtZhZttTPZ..',
    '..ZPTTthtTTTPZ..',
    '..ZPPPPPPPPPPZ..',
    '...TZZGGGGZZT...',
    '......TGGT......',
    '.......ZG.......',
    '......pZGT......',
    '......TZGT......',
    '....TZZ..ZZT....',
  ],
  bell: [
    '................',
    '.TZZ........ZZT.',
    '.ZGG...TT...GGZ.',
    '..G...TZZT...G..',
    '..G..ZGggGZ..G..',
    '..GGZGGGGGGZGG..',
    '....ZGpPPpGZ....',
    '....ZGGGGGGZ....',
    '...ZGGgGGgGGZ...',
    '...ZGPpPPpPGZ...',
    '..ZGGGGGGGGGGZ..',
    '.TTTTTTTTTTTTTT.',
    '....ZG....GZ....',
    '...ZG......GZ...',
    '...Zg......gZ...',
    '..TZZ......ZZT..',
  ],
  choirmother: [
    '.T.....TT.....T.',
    '..T....TT....T..',
    '.gGT...TT...TGg.',
    '.GG.TTTZZTTT.GG.',
    '...TZgGGGGgZT...',
    '..TZGGGGrGGGZT..',
    '..ZGhpphGGGGGZ..',
    '..ZgZZZZGhpphZ..',
    '..ZGGhpphZZZZZ..',
    '..ZgGZZZZGGhpZ..',
    '..ZGhpphGGGZZZ..',
    '..TZZZZZGhpphT..',
    '...TZGGGGZZZT...',
    '....TZhpphZT....',
    '.....TZZZZT.....',
    '......T..T......',
  ],
  // -- Quarantine
  specimen: [
    '................',
    '.....GGggGG.....',
    '....GgGGGGgG....',
    '...ZEEEEEEEEZ...',
    '...EedddddddE...',
    '...EeddQQdddE...',
    '...EedQZZQddE...',
    '...EedQZqZQdE...',
    '...EeddQZZQdE...',
    '...EedddQQddE...',
    '...EedddddddE...',
    '...ZEEEEEEEEZ...',
    '...GGrGGGGgGG...',
    '..G.g......g.G..',
    '.G..g......g..G.',
    '.g...g....g...g.',
  ],
  cage: [
    '................',
    '..gGGGGGGGGGGGg.',
    '.......GrG......',
    '....ZGGGGGGGZ...',
    '....g.g.g.g.G...',
    '....g.g.g.g.G...',
    '....g.g.g.g.G...',
    '....g.g.g.g.G...',
    '....g.g.g.g.G...',
    '....ZGGGGGGGZ...',
    '...GZ.......ZG..',
    '..G...........G.',
    '..G...........G.',
    '..gG.........Gg.',
    '...gg.......gg..',
    '................',
  ],
  cageB: [ // idle: rotor edge-on
    '................',
    '......GGGGG.....',
    '.......GrG......',
    '....ZGGGGGGGZ...',
    '....g.g.g.g.G...',
    '....g.g.g.g.G...',
    '....g.g.g.g.G...',
    '....g.g.g.g.G...',
    '....g.g.g.g.G...',
    '....ZGGGGGGGZ...',
    '...GZ.......ZG..',
    '..G...........G.',
    '..G...........G.',
    '..gG.........Gg.',
    '...gg.......gg..',
    '................',
  ],
  sprayer: [
    '................',
    '.......ww.......',
    '......wwwe..ZZ..',
    '......rrrw.ZqQZ.',
    '.......we..ZqQZ.',
    '.......EE..ZrRZ.',
    '....ewwwwwwZqQZ.',
    '...eGwwwwwweZZ..',
    '..GG.wwwwwwe....',
    '.GG..ewwwwwe....',
    'gG...ewwwwe.....',
    'r....ww..ww.....',
    '.....ww..ww.....',
    '.....ew..we.....',
    '.....gg..gg.....',
    '....ggG..Ggg....',
  ],
  gatekeeper: [
    '.qqqqqqqqqqqqqq.',
    '.QrQQQQQQQQQQrQ.',
    '.qQhhGZZZZGhhQq.',
    '.qQhGZgGGgZGhQq.',
    '.qQhZgGhhGgZhQq.',
    '.qQhZGhhrhGZhQq.',
    '.qQhZgGhhGgZhQq.',
    '.qQhGZgGGgZGhQq.',
    '.qQhGZZZZZZGhQq.',
    '.qQhgGhZZhGghQq.',
    '.qQgGhhhZhhGgQq.',
    '.qQgghhhZhhggQq.',
    '.qQhgGhhhhGghQq.',
    '.qQhhgGhhGghhQq.',
    '.QRhRhRhRhRhRhQ.',
    '.QQQQQQQQQQQQQQ.',
  ],
  // -- Graveyard of Signatures
  citizen: [
    '................',
    '......qqq....q..',
    '.....qqqqQ..qq..',
    '.....qhqqQ..qQ..',
    '......qhQ...qQ..',
    '.......Q....A...',
    '....AAqqqAAAA...',
    '...AaAAqAAaA....',
    '...Aa.AqAAa.....',
    '...Aa.AqhAa.....',
    '...Aa.AAAAa.....',
    '...qQ.AAAAA.....',
    '......Aa.Aa.....',
    '......Aa.Aa.....',
    '......Aa.Aa.....',
    '.....QQ...QQ....',
  ],
  burrow: [
    '................',
    '................',
    '........GAAG....',
    '........AvhA....',
    '.........AAZ....',
    '.......GZZ......',
    '.....GAAaAAG....',
    '....aAZAZZAZA...',
    '...aA.ZAaaA.A...',
    '..aA..AZAAZ.a...',
    '.aA...ZAaaZ.A...',
    'ga....hZAAZh.g..',
    'ggQQhhhhhhhhhQqQ',
    '.QQqQhhhhhhhQQq.',
    '..QQQQQQQQQQQQ..',
    '................',
  ],
  mourner: [
    '................',
    '................',
    '......ZGGZ......',
    '.....aZggZa.....',
    '....a.ZGGZ.a....',
    '...a.AGZZGA.a...',
    '...a.A.ZZ.A.a...',
    '..a..A.ZZ.A..a..',
    '..A..a.ZZ.a..A..',
    '..a..A.ZZ.A..a..',
    '..A..g.ZZ.g..A..',
    '..a....ZZ....a..',
    '..g...Z..Z...g..',
    '......Z..Z......',
    '......Z..Z......',
    '.....GZ..ZG.....',
  ],
  tomb: [
    '................',
    '................',
    '................',
    '.....GGGGGG.....',
    '....GgggggGG....',
    '....GZZaZZG.....',
    '..GGGGGGGGGGGG..',
    '..G.qqqqqqqq.G..',
    '..g.qQQqQQQq.g..',
    '..G.qqqqqqqq.G..',
    '..g.qQQQqQQq.g..',
    '..GGqqqqqqqqGG..',
    '....GZZZZZZG....',
    '...GZZ.GG.ZZG...',
    '...GgZgZZgZgG...',
    '...GGGGGGGGGG...',
  ],
  crow: [
    '................',
    '................',
    '.Z..............',
    '.TZ.............',
    '.tTZ......TZ....',
    '..tTZ....TZrZgg.',
    '..ttTZ...TTZZT..',
    '...ttTZTTTTZT...',
    '...htTTTTTTT....',
    '....htTTTTT.....',
    '......TTTTt.....',
    '.....tTht.......',
    '....tT..g.g.....',
    '...t....g.g.....',
    '.......gg.gg....',
    '................',
  ],
  heir: [
    '......GGGG......',
    '.....GZTTZG.....',
    '....GZTvTTZG....',
    '..GGZEeeeeEZGG..',
    '.G..ZEdZZdEZ..G.',
    'G...ZEdssdEZ...G',
    'G...ZEdSSdEZ...G',
    'G...ZEsSSsEZ...G',
    'g...ZEdSSdEZ...g',
    'gG..ZEdSdSEZ..Gg',
    '.gg.ZEEEEEEZ.gg.',
    '....GZZZZZZG....',
    '...GZgGZZGgZG...',
    '...ZZZZZZZZZZ...',
    '...GZ.ZGGZ.ZG...',
    '...GG.GGGG.GG...',
  ],
  // -- Silent Stratum
  lacuna: [
    '................',
    '.....ggGGgg..w..',
    '...gGGZZZZGGg...',
    '..gGZhhhhhhZGg..',
    '..GZhhhhhhhhZG..',
    '.gGZhhhhhhhhZGg.',
    '.GZhhhhhhhhhh.G.',
    '.GZhhhhhhhhhh...',
    '.GZhhhhhhhhhh.w.',
    '.gGZhhhhhhhhZGg.',
    '..GZhhhhhhhhZG..',
    '..gGZhhhhhhZGg..',
    '...gGGZZZZGGg...',
    '.w...ggGGgg.....',
    '................',
    '................',
  ],
  pointer: [
    '................',
    '................',
    '.............w..',
    '............we..',
    '...........TZ...',
    '..........hZ....',
    '.........hZ.....',
    '........hZ......',
    '.......hZ.......',
    '......hZ........',
    '.....hZ.........',
    '....tZ..........',
    '..gGg...........',
    '..G.G...........',
    '..gGg...........',
    '................',
  ],
  pointerB: [ // idle: the tip gutters out
    '................',
    '................',
    '................',
    '............g...',
    '...........TZ...',
    '..........hZ....',
    '.........hZ.....',
    '........hZ......',
    '.......hZ.......',
    '......hZ........',
    '.....hZ.........',
    '....tZ..........',
    '..gGg...........',
    '..G.G...........',
    '..gGg...........',
    '................',
  ],
  stalker: [
    '................',
    '......ZGGZ......',
    '.....ZgeegZ.....',
    '.....GZrZZG.....',
    '......ZGGZ......',
    '.....G.GG.G.....',
    '....G..G.G.G....',
    '....G..G..G.G...',
    '...G...G..G..G..',
    '...G...g...G.G..',
    '..G....G...G..G.',
    '..G....G...G..G.',
    '.G.....G....G..G',
    '.G.....G....G..G',
    '.G.....G....G...',
    '.g.....g....g...',
  ],
  monolith: [
    '................',
    '.....ZZZZZT.....',
    '.....ZttttT.....',
    '.....ZttetT.....',
    '.....ZttwtT.....',
    '.....ZttwtT.....',
    '.....ZttwtT.....',
    '.....ZttwtT.....',
    '.....ZttwtT.....',
    '.....ZttwtT.....',
    '.....ZttwtT.....',
    '.....ZttwtT.....',
    '.....ZttetT.....',
    '.....ZttttT.....',
    '....ZTTTTTTT....',
    '................',
  ],
  faceless: [
    '.......ee.......',
    '......eeeE......',
    '......eeeE......',
    '.......eE.......',
    '.......EE.......',
    '......TwwT......',
    '....ZZZwwZZT....',
    '....Z.ZThZ.T....',
    '....Z.ZThZ.T....',
    '....Z.ZTTZ.T....',
    '....Z.ZTTZ.T....',
    '....G.ZTTZ.G....',
    '....e.Z..Z.e....',
    '......Z..T......',
    '......Z..T......',
    '.....ZZ..TZ.....',
  ],
  mirror: [
    '................',
    '..e...TTTT......',
    '.Ee..TThhTT.....',
    '.Ee..ThhhhT.....',
    '.Ee..Rrrrrr.....',
    '.Ee..hQqqQh.....',
    '.Ee...hQQh......',
    '.Ee.zZZhhZZz.ww.',
    'qQQqGZzZZzGGz...',
    '.SS.GZzzZZzzZG..',
    '.N..gGZzzZZzzZG.',
    '.....zzzZZzzzS..',
    '....zzzZZzzz....',
    '....Gz.ZZ.zG....',
    '....z.hTTh.z....',
    '.....hh..hh.....',
  ],
  // -- The Root
  kernel: [
    '................',
    '................',
    '......GggG......',
    '....g.RrrR.g....',
    '...g.RrcwrR.g...',
    '....RRrccrRR....',
    '.ggGRrrrRrrRGgg.',
    '...RrwrrRrwrR...',
    '..gGRrrrRrrrRGg.',
    '.g.RrrrrRrrrR..g',
    '...GRrrrRrrrRG..',
    '.ggGRRrrRrrRRGgg',
    '....RRrrRrrRR...',
    '...g.RRRRRRR.g..',
    '..g..........g..',
    '................',
  ],
  kernelB: [ // idle: legs spasm
    '................',
    '................',
    '......GggG......',
    '...g..RrrR..g...',
    '..g..RrcwrR..g..',
    '....RRrccrRR....',
    '..gGRrrrRrrRGg..',
    '.g.RrwrrRrwrR.g.',
    '...GRrrrRrrrRG..',
    '..gRrrrrRrrrRg..',
    '.g.GRrrrRrrrRG.g',
    '...GRRrrRrrRRG..',
    '..g.RRrrRrrRR.g.',
    '.g..gRRRRRRRg..g',
    '................',
    '................',
  ],
  daemon: [
    '................',
    '...gG......Gg...',
    '..G..........G..',
    '..G...ZTTZ...G..',
    '..G..ZTccTZ..G..',
    '..G..TcwwcT..G..',
    '.G...TcwwcT...G.',
    'G....ZTccTZ....G',
    '.G....ZTTZ....G.',
    '..G....ZZ....G..',
    '..G....Z.....G..',
    '..G.....Z....G..',
    '..G....Z.....G..',
    '...gG..z....Gg..',
    '................',
    '................',
  ],
  firewall: [
    '................',
    '..o....y...o....',
    '.oyo..oyo..yo.o.',
    '.oOyooyOyooOyoy.',
    '.TTTTTTTTTTTTTT.',
    '.TRrRTRrrRTRrRT.',
    '.TRoRTRoRRTRRRT.',
    '.TTTTTTTTTTTTTT.',
    '.TRRTRrRRTRrRRT.',
    '.TRrTRRoRTRRoRT.',
    '.TTTTTTTTTTTTTT.',
    '.TRrRTRRrRTRrRT.',
    '.TRRRTRrRRTRRRT.',
    '.TTTTTTTTTTTTTT.',
    '.ZZZZZZZZZZZZZZ.',
    '................',
  ],
  collector: [
    '................',
    '................',
    '..GGGGGGGGGGGG..',
    '.GgggggggggggZG.',
    '.GZZZZcZZZZZZZG.',
    '.GRhRhRhRhRhRhG.',
    '.GZZZZZZZZZZZZG.',
    'gGgGgGgGgGgGgGGg',
    'gGhGhhGhGhhGhhGg',
    'gGhhhhhhhhhhhhGg',
    'gGhhGhhGhGhhGhGg',
    'gGGgGgGgGgGgGgGg',
    '.GZZZZZZZZZZZZG.',
    '.GZGZGZGZGZGZGG.',
    '.GGGGGGGGGGGGGG.',
    '................',
  ],
});
