'use strict';
// STRATUM core: palette, sprites, item kinds and combat rules. World content lives in world.js.

// One char per color. '.' = transparent. Sprites get an auto dark outline.
const PAL = {
  k: '#0a0b10', w: '#f2f0ea', g: '#9ea2ad', G: '#4f535e', y: '#ffc23a', Y: '#b97a12',
  o: '#ff8a3c', O: '#fff1b0', r: '#ff3b4e', R: '#8f1626', b: '#4ec3ff', B: '#1a5a9e',
  c: '#6ff7ff', C: '#1a8fa0', v: '#39ff9e', V: '#0f5a3c', q: '#c9c6bd', Q: '#6e6b66',
  s: '#e8d6c8', S: '#a8928a', z: '#1d2029', Z: '#3a3f4f', h: '#08080c', t: '#15171e', T: '#262a36',
  p: '#b98cff', P: '#5a3a8f', e: '#dfe9f2', E: '#8aa2b8', n: '#c77a3a', N: '#5e3518', l: '#ffd9a0',
};

const SPRITES = {
  heroD: [
    '................',
    '.....hhhhhh.....',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhsssssshh...',
    '...hsccccccsh...',
    '....ssssssss....',
    '.....ssSSss.....',
    '....zzzZZzzz....',
    '...zzzzZZzzzz...',
    '..zzzzzZZzzzzz..',
    '..szzzzZZzzzzGG.',
    '..zzzzzZZzzzzGc.',
    '..zzzz.ZZ.zzzz..',
    '...zzz....zzz...',
    '...GGG....GGG...',
  ],
  heroU: [
    '................',
    '.....hhhhhh.....',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '....hhhhhhhh....',
    '.....ssssss.....',
    '....zzzzzzzz....',
    '...zzzzzzzzzz...',
    '..zzzzzzzzzzzz..',
    '.GGzzzzzzzzzzs..',
    '.cGzzzzzzzzzz...',
    '..zzzzzzzzzzzz..',
    '...zzz....zzz...',
    '...GGG....GGG...',
  ],
  heroR: [
    '................',
    '.....hhhhhh.....',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhsssss...',
    '...hhhhhsccccc..',
    '....hhhssssss...',
    '.....hhsssss....',
    '.....zzzzzz.....',
    '....zzzzzzzz....',
    '....zzzzzzzssGGG',
    '....zzzzzzz..Gc.',
    '....zzzzzzzz....',
    '....zzzzzzzzz...',
    '....zzz...zzz...',
    '....GGG...GGG...',
  ],
  mite: [
    '................', '................', '................', '................', '................',
    '......gggg......',
    '....gggggggg....',
    '...gGgggggggG...',
    '...ggggrrgggg...',
    '...GgggrrgggG...',
    '....GGGGGGGG....',
    '..G.G.G..G.G.G..',
    '.G..G..GG..G..G.',
  ],
  miteB: [ // idle: legs mid-step
    '................', '................', '................', '................', '................',
    '......gggg......',
    '....gggggggg....',
    '...gGgggggggG...',
    '...ggggrrgggg...',
    '...GgggrrgggG...',
    '....GGGGGGGG....',
    '...G.G.GG.G.G...',
    '..G.G..GG..G.G..',
  ],
  wisp: [
    '................', '................',
    '.......c........',
    '...c...c...c....',
    '....c..c..c.....',
    '.....cwwwc......',
    '..ccwwOOOwwcc...',
    '....cwOOOwc.....',
    '.....cwwwc......',
    '....c..c..c.....',
    '...c...c...c....',
    '.......c........',
  ],
  wispB: [ // idle: rays twinkle
    '................', '................',
    '.......c........',
    '.......c........',
    '.......c........',
    '.....cwwwc......',
    '.cccwwOOOwwccc..',
    '....cwOOOwc.....',
    '.....cwwwc......',
    '.......c........',
    '.......c........',
    '.......c........',
  ],
  husk: [
    '................', '................',
    '......qqqq......',
    '.....qqqqqq.....',
    '.....qkqqkq.....',
    '.....qqqqqq.....',
    '......qkkq......',
    '....QQQQQQQQ....',
    '...QQcQQQQQQQ...',
    '..qQccQQQQQQQq..',
    '..q.QQQQQQcQ.q..',
    '....QQQQQQcc....',
    '....QQQ..QQQ....',
    '....QQ....QQ....',
    '....qq....qq....',
  ],
  sanitizer: [
    '......wwww......',
    '.....wwwwww.....',
    '.....wrrrrw.....',
    '.....wwwwww.....',
    '......gwwg......',
    '...wwwwwwwwww...',
    '..wwgwwwwwwgww..',
    '..ww.wwwwww.ww..',
    '..ww.wwggww.ww..',
    '..gg.wwwwww.gg..',
    '..rr.wwwwww.rr..',
    '.....ww..ww.....',
    '.....ww..ww.....',
    '.....ww..ww.....',
    '....www..www....',
  ],
  sanitizerL: [ // idle: visor glances left
    '......wwww......',
    '.....wwwwww.....',
    '.....wrrwww.....',
    '.....wwwwww.....',
    '......gwwg......',
    '...wwwwwwwwww...',
    '..wwgwwwwwwgww..',
    '..ww.wwwwww.ww..',
    '..ww.wwggww.ww..',
    '..gg.wwwwww.gg..',
    '..rr.wwwwww.rr..',
    '.....ww..ww.....',
    '.....ww..ww.....',
    '.....ww..ww.....',
    '....www..www....',
  ],
  serpent: [
    '................',
    '..........ggg...',
    '.........gvkgg..',
    '........ggggggg.',
    '........ggGg....',
    '.......ggG......',
    '......ggG.......',
    '.....ggG........',
    '....gggG........',
    '....ggGgg.......',
    '.....gGggg......',
    '......gGggg.....',
    '.......gGgg.....',
    '........ggg.....',
    '.........v......',
  ],
  serpentT: [ // idle: tongue flick
    '................',
    '..........ggg...',
    '.........gvkgg..',
    '........gggggggr',
    '........ggGg...r',
    '.......ggG......',
    '......ggG.......',
    '.....ggG........',
    '....gggG........',
    '....ggGgg.......',
    '.....gGggg......',
    '......gGggg.....',
    '.......gGgg.....',
    '........ggg.....',
    '.........v......',
  ],
  mason: [
    '................',
    '...GGGGGGGGGG...',
    '...GyyyyyyyyG...',
    '...GyvvyyvvyG...',
    '...GyyyyyyyyG...',
    '.GGGGGGGGGGGGGG.',
    'GyGykykykykykGyG',
    'GyGkykykykykyGyG',
    'GGGGGGGGGGGGGGGG',
    'GgG.GggggggG.GgG',
    'GgG.GggggggG.GgG',
    'yyy.GGGGGGGG.yyy',
    '....GGG..GGG....',
    '....ggg..ggg....',
    '...GGGG..GGGG...',
  ],
  masonB: [ // idle: blink
    '................',
    '...GGGGGGGGGG...',
    '...GyyyyyyyyG...',
    '...GyGGyyGGyG...',
    '...GyyyyyyyyG...',
    '.GGGGGGGGGGGGGG.',
    'GyGykykykykykGyG',
    'GyGkykykykykyGyG',
    'GGGGGGGGGGGGGGGG',
    'GgG.GggggggG.GgG',
    'GgG.GggggggG.GgG',
    'yyy.GGGGGGGG.yyy',
    '....GGG..GGG....',
    '....ggg..ggg....',
    '...GGGG..GGGG...',
  ],
  drone: [
    '................', '................',
    '..gg........gg..',
    '.gGGg......gGGg.',
    '..gg..gggg..gg..',
    '...g.gGGGGg.g...',
    '....gGrrrrGg....',
    '....gGGGGGGg....',
    '.....gGGGGg.....',
    '......g..g......',
    '.....g....g.....',
  ],
  droneB: [ // idle: rotors edge-on
    '................', '................', '................',
    'gggg........gggg',
    '...g..gggg..g...',
    '...g.gGGGGg.g...',
    '....gGrrrrGg....',
    '....gGGGGGGg....',
    '.....gGGGGg.....',
    '......g..g......',
    '.....g....g.....',
  ],
  turret: [
    '................',
    '......GGGG......',
    '.....GggggG.....',
    '....GgrrrrgG....',
    '....GgrOOrgG....',
    '....GgrrrrgG....',
    '.....GggggG.....',
    '..GGGGGGGGGGGG..',
    '..GggggggggggG..',
    '...GGGGGGGGGG...',
    '....Gg....gG....',
    '...GGg....gGG...',
    '..GGG......GGG..',
  ],
  turretL: [ // idle: swivelled left
    '................',
    '......GGGG......',
    '.....GggggG.....',
    '....rrrrgggG....',
    '..GGrOOrgggG....',
    '....rrrrgggG....',
    '.....GggggG.....',
    '..GGGGGGGGGGGG..',
    '..GggggggggggG..',
    '...GGGGGGGGGG...',
    '....Gg....gG....',
    '...GGg....gGG...',
    '..GGG......GGG..',
  ],
  hound: [
    '................', '................', '................',
    '..........GGG...',
    '.........GgrgG..',
    '.GG......GgggGG.',
    '..GGGGGGGGgggG..',
    '..GggggggggGG...',
    '..GgGGGGGGgG....',
    '..Gg.....Gg.....',
    '..Gg.....Gg.....',
    '.GGg....GGg.....',
  ],
  houndP: [ // idle: panting, tail down
    '................', '................', '................',
    '..........GGG...',
    '.........GgrgG..',
    '.........GgggGG.',
    '.GGGGGGGGGgggGr.',
    '..GggggggggGG...',
    '..GgGGGGGGgG....',
    '..Gg.....Gg.....',
    '..Gg.....Gg.....',
    '.GGg....GGg.....',
  ],
  ghost: [
    '................',
    '......eeee......',
    '.....eeeeee.....',
    '....eekeekee....',
    '....eekeekee....',
    '....eeeeeeee....',
    '....eeekkeee....',
    '...eeeeeeeeee...',
    '..eEeeeeeeeeEe..',
    '..E.eeeeeeee.E..',
    '....eeeeeeee....',
    '....eEeeeeEe....',
    '....E.eEEe.E....',
    '.......E........',
  ],
  surgeon: [
    '................',
    '.....wwwwww.....',
    '....wwwwwwww....',
    '....wbbbbbbw....',
    '....wwwwwwww....',
    '.....wwrrww.....',
    '..g..wrrrrw..g..',
    '..g.wwwrrwww.g..',
    '..gwwwwwwwwwwg..',
    '..g.wwwwwwww.g..',
    '..w.wwwwwwww.w..',
    '.....ww..ww.....',
    '.....gg..gg.....',
    '.....gg..gg.....',
    '....ggg..ggg....',
  ],
  surgeonB: [ // idle: scalpels raised
    '................',
    '.....wwwwww.....',
    '....wwwwwwww....',
    '....wbbbbbbw....',
    '..g.wwwwwwww.g..',
    '..g..wwrrww..g..',
    '..g..wrrrrw..g..',
    '..g.wwwrrwww.g..',
    '..wwwwwwwwwwww..',
    '....wwwwwwww....',
    '....wwwwwwww....',
    '.....ww..ww.....',
    '.....gg..gg.....',
    '.....gg..gg.....',
    '....ggg..ggg....',
  ],
  choir: [
    '................',
    '.p............p.',
    '.pp..........pp.',
    '.ppp..wwww..ppp.',
    '.pPpp.wkkw.ppPp.',
    '..pPppwwwwppPp..',
    '...pPpwkkwpPp...',
    '....ppwwwwpp....',
    '......wwww......',
    '.......ww.......',
    '......p..p......',
    '.....p....p.....',
  ],
  choirB: [ // idle: wings down
    '................', '................', '................',
    '.p....wwww....p.',
    '.pp...wkkw...pp.',
    '.ppp..wwww..ppp.',
    '.pPpp.wkkw.ppPp.',
    '..pPppwwwwppPp..',
    '...pPpwwwwpPp...',
    '....pp.ww.pp....',
    '......p..p......',
    '.....p....p.....',
  ],
  knight: [
    '................',
    '.....GGGGGG.....',
    '....GggggggG....',
    '....GgrrrrgG....',
    '....GggggggG....',
    '...GGGGGGGGGG...',
    '..GgGggggggGgG..',
    '..GgGggyyggGgG..',
    '..GgGggggggGgG..',
    '..GGGggggggGGG..',
    '.....GggggG.....',
    '....GGG..GGG....',
    '....Ggg..ggG....',
    '...GGGG..GGGG...',
  ],
  knightL: [ // idle: visor glances left
    '................',
    '.....GGGGGG.....',
    '....GggggggG....',
    '....GrrrgggG....',
    '....GggggggG....',
    '...GGGGGGGGGG...',
    '..GgGggggggGgG..',
    '..GgGggyyggGgG..',
    '..GgGggggggGgG..',
    '..GGGggggggGGG..',
    '.....GggggG.....',
    '....GGG..GGG....',
    '....Ggg..ggG....',
    '...GGGG..GGGG...',
  ],
  warden: [
    '..r..........r..',
    '..rr.gggggg.rr..',
    '...rgwwwwwwgr...',
    '...gwwwwwwwwg...',
    '...gwkkwwkkwg...',
    '...gwwwrrwwwg...',
    '...gwwwrrwwwg...',
    '....gwwwwwwg....',
    '..zzzgwwwwgzzz..',
    '.zzZzzggggzzZzz.',
    'zzZzzzzzzzzzzZzz',
    'zZzzrzzzzzzrzzZz',
    'zZz.zzzzzzzz.zZz',
    'zz..zzzzzzzz..zz',
    '.r..zzz..zzz..r.',
    '....rr....rr....',
  ],
  wardenE: [ // idle: eyes lit
    '..r..........r..',
    '..rr.gggggg.rr..',
    '...rgwwwwwwgr...',
    '...gwwwwwwwwg...',
    '...gwrrwwrrwg...',
    '...gwwwrrwwwg...',
    '...gwwwrrwwwg...',
    '....gwwwwwwg....',
    '..zzzgwwwwgzzz..',
    '.zzZzzggggzzZzz.',
    'zzZzzzzzzzzzzZzz',
    'zZzzrzzzzzzrzzZz',
    'zZz.zzzzzzzz.zZz',
    'zz..zzzzzzzz..zz',
    '.r..zzz..zzz..r.',
    '....rr....rr....',
  ],
  archivist: [
    '................',
    '..GGGGGGGGGGGG..',
    '..GVVVVVVVVVVG..',
    '..GVVvVVVVvVVG..',
    '..GVVvVVVVvVVG..',
    '..GVVVVVVVVVVG..',
    '..GVVVvvvvVVVG..',
    '..GVVVVVVVVVVG..',
    '..GGGGGGGGGGGG..',
    '......GGGG......',
    '....GGGGGGGG....',
    '...GgggggggggG..',
    '...GgGgGgGgGgG..',
    '...GGGGGGGGGGG..',
  ],
  lambda: [
    '................',
    '..CCCCCCCCCCCC..',
    '..C..........C..',
    '..C..cc......C..',
    '..C...cc.....C..',
    '..C....cc....C..',
    '..C....ccc...C..',
    '..C...cc.cc..C..',
    '..C..cc...cc.C..',
    '..C.cc.....ccC..',
    '..C..........C..',
    '..CCCCCCCCCCCC..',
  ],
  brann: [
    '................',
    '.....NNNNNN.....',
    '....NnnnnnnN....',
    '....NnyyyynN....',
    '....ssssssss....',
    '....skssssks....',
    '....ssnnnnss....',
    '.....nnnnnn.....',
    '...nnnnnnnnnn...',
    '..nnnNnnnnNnnn..',
    '..snnNnnnnNnnsGG',
    '...nnNnnnnNnn.gG',
    '...NNNN..NNNN...',
    '...NNN....NNN...',
  ],
  ohm: [
    '................',
    '.....ZZZZZZ.....',
    '....ZZZZZZZZ....',
    '...ZZwwwwwwZZ...',
    '...ZwqqqqqqwZ...',
    '...ZwqkqqkqwZ...',
    '...ZwqqqqqqwZ...',
    '...ZZwwwwwwZZ...',
    '..ZZZZZZZZZZ.l..',
    '..ZZZZZZZZZZsw..',
    '..ZZZZZZZZZZ.w..',
    '..ZZZZZZZZZZZ...',
    '...ZZZZZZZZZZ...',
    '...ZZZZZZZZZZ...',
  ],
  pip: [
    '................', '................', '................', '................',
    '......gggg......',
    '.....gGGGGg.....',
    '....gGckckGg....',
    '....gGccccGg....',
    '....gGcwwcGg....',
    '.....gGGGGg.....',
    '......g..g......',
    '.....c....c.....',
  ],
  broker: [
    '................',
    '.....ZZZZZZ.....',
    '....ZZZZZZZZ....',
    '...ZZZssssZZZ...',
    '...ZZoOssoOZZ...',
    '...ZZssssssZZ...',
    '....ZssSSssZ....',
    '....ZZZZZZZZ....',
    '...ZZZyZZyZZZ...',
    '..ZZZZZyyZZZZZ..',
    '..ZZZZZZZZZZZZ..',
    '..sZZZZZZZZZZs..',
    '...ZZZZZZZZZZ...',
    '...ZZZZ..ZZZZ...',
    '...GGG....GGG...',
  ],
  fabricator: [
    '................',
    '.....GGGGGG.....',
    '.....GvvvvG.....',
    '.....GGGGGG.....',
    '...GGGGGGGGGG...',
    '...GggggggggG...',
    '...GgkkkkkkgG...',
    '...GgkoooOkgG...',
    '...GgkkkkkkgG...',
    '...GggggggggG...',
    '...GgvgvgvggG...',
    '...GGGGGGGGGG...',
    '..GggggggggggG..',
    '..GGGGGGGGGGGG..',
  ],
  root: [
    '.....GGGGGG.....',
    '....GzzzzzzG....',
    '....GzcccczG....',
    '....GzcwwczG....',
    '....GzcwwczG....',
    '....GzcccczG....',
    '....GzzzzzzG....',
    '....GzvzvzzG....',
    '....GzzzzzzG....',
    '....GzvzzvzG....',
    '....GzzzzzzG....',
    '...GGGGGGGGGG...',
    '..GggggggggggG..',
    '..GGGGGGGGGGGG..',
  ],
  cardY: [
    '................', '................', '................', '................',
    '...yyyyyyyyyy...',
    '...yggyyyyyyy...',
    '...yggyyyyyyy...',
    '...yyyyyyyyyy...',
    '...YYYYYYYYYY...',
    '...yyyyyyyyyy...',
    '...yyyyyyYYYy...',
    '...yyyyyyyyyy...',
  ],
  doorY: [
    'GGGGGGGGGGGGGGGG',
    'GyyyyyyyyyyyyyyG',
    'GGGGGGGGGGGGGGGG',
    'GggggggggggggggG',
    'GGGGGGGGGGGGGGGG',
    'GggggggggggggggG',
    'GGGGGGyyyyGGGGGG',
    'GggggyYYYYyggggG',
    'GGGGGyYkkYyGGGGG',
    'GggggyYYYYyggggG',
    'GGGGGGyyyyGGGGGG',
    'GggggggggggggggG',
    'GGGGGGGGGGGGGGGG',
    'GggggggggggggggG',
    'GYYYYYYYYYYYYYYG',
    'GGGGGGGGGGGGGGGG',
  ],
  battery: [
    '................', '................',
    '......gggg......',
    '.....GGGGGG.....',
    '.....GvvvvG.....',
    '.....GvvyvG.....',
    '.....GvyvvG.....',
    '.....GyyyvG.....',
    '.....GvvyvG.....',
    '.....GvyvvG.....',
    '.....GvvvvG.....',
    '.....GVVVVG.....',
    '.....GGGGGG.....',
  ],
  ram: [
    '................', '................', '................', '................',
    '.BBBBBBBBBBBBBB.',
    '.BbbbbbbbbbbbbB.',
    '.BbkkbkkbkkbkkB.',
    '.BbkkbkkbkkbkkB.',
    '.BbbbbbbbbbbbbB.',
    '.ByyyyyyB.yyyyB.',
  ],
  chipA: [
    '................', '................',
    '.....g.g.g.g....',
    '....rrrrrrrrr...',
    '..g.rwrrrrrrR.g.',
    '....rrRRRRRrR...',
    '..g.rrROOORrR.g.',
    '....rrROOORrR...',
    '..g.rrRRRRRrR.g.',
    '....rrrrrrrrR...',
    '....RRRRRRRRR...',
    '.....g.g.g.g....',
  ],
  lance: [
    '................', '................', '................', '................', '................',
    '...GGGGGGGGGGcc.',
    '..GgggggggggGGc.',
    '..GGGGGGGGGGG...',
    '..GGzz.G........',
    '...Gzz..........',
    '...Gzz..........',
    '...GGG..........',
  ],
  lattice: [
    '................', '................',
    '...gg......gg...',
    '..gGgg....ggGg..',
    '..gggggggggggg..',
    '...gcggggggggg..',
    '...gcgGggGggg...',
    '...gggGggGggg...',
    '...ggGggggGgg...',
    '....gGggggGg....',
    '....ggGggGgg....',
    '.....gggggg.....',
    '......gggg......',
  ],
  floppy: [
    '................', '................', '................',
    '...BBBBBBBBBB...',
    '...BBggggggBB...',
    '...BBggGgggBB...',
    '...BBggGgggBB...',
    '...BBBBBBBBBB...',
    '...BwwwwwwwwB...',
    '...BwrrrrrrwB...',
    '...BwwwwwwwwB...',
    '...BBBBBBBBBB...',
  ],
  compass: [
    '................', '................', '................',
    '......gggg......',
    '....ggccccgg....',
    '...gccccrcccg...',
    '...gcccrrcccg...',
    '...gccckwcccg...',
    '...gcccbbcccg...',
    '...gccccbcccg...',
    '....ggccccgg....',
    '......gggg......',
  ],
  shard: [
    '................', '................',
    '.......y........',
    '......yOy.......',
    '......yOy.......',
    '.....yyOyy......',
    '.....yOyyY......',
    '....yyOyyYY.....',
    '....yOyyyYY.....',
    '.....yyyyY......',
    '......yyY.......',
    '.......y........',
  ],
  note: [
    '................', '................', '................', '................', '................', '................',
    '....o.o...o.....',
    '...ooo.o.ooo....',
    '....o..o..o.o...',
    '...o.o.oo.o.....',
  ],
  credit: [
    '................', '................', '................',
    '.....yyyyyy.....',
    '....yOOyyyyY....',
    '...yOyykkyyyY...',
    '...yOykyyyyyY...',
    '...yyykyyyyyY...',
    '...yyyykkyyyY...',
    '....yyyyyyyY....',
    '.....YYYYYY.....',
  ],
};

// Named palette swaps: [base sprite, {from: to}]. Monster rosters add their own swaps in world.js.
const VARIANTS = {
  cardB: ['cardY', { y: 'b', Y: 'B' }],
  cardR: ['cardY', { y: 'r', Y: 'R' }],
  doorB: ['doorY', { y: 'b', Y: 'B' }],
  doorR: ['doorY', { y: 'r', Y: 'R' }],
  supercap: ['battery', { v: 'c', V: 'C', y: 'w' }],
  chipD: ['chipA', { r: 'b', R: 'B' }],
  rootDark: ['root', { c: 'T', w: 't', v: 'Z' }],
  serverDead: ['root', { c: 'Z', w: 'T', v: 'z' }],
  wanderer: ['broker', { Z: 'Q', o: 'G', O: 'g', y: 'Q', S: 's' }],
  drill: ['lance', { G: 'N', g: 'n', c: 'y', z: 'N' }],
};

// Map tile -> item kind. Values scale by zone (see BALANCE in balance.js).
const ITEMS = {
  y: { kind: 'key', key: 'y', name: 'Amber Keycard', sprite: 'cardY' },
  b: { kind: 'key', key: 'b', name: 'Cyan Keycard', sprite: 'cardB' },
  r: { kind: 'key', key: 'r', name: 'Crimson Keycard', sprite: 'cardR' },
  h: { kind: 'hp', name: 'Li-ion Cell', sprite: 'battery' },
  H: { kind: 'hp', name: 'Supercapacitor', sprite: 'supercap' },
  a: { kind: 'atk', name: 'CPU Core', sprite: 'chipA' },
  d: { kind: 'def', name: 'ECC RAM', sprite: 'ram' },
  w: { kind: 'atk', gear: true, sprite: 'lance' },
  e: { kind: 'def', gear: true, sprite: 'lattice' },
  v: { kind: 'antivirus', name: 'Antivirus Disk', sprite: 'floppy' },
  c: { kind: 'compass', name: 'Phase Compass', sprite: 'compass' },
  '*': { kind: 'shard', name: 'Memory Shard', sprite: 'shard' },
};

const DOORS = { Y: 'y', B: 'b', R: 'r' };
const KEY_NAMES = { y: 'Amber', b: 'Cyan', r: 'Crimson' };

const ABILITIES = {
  swift: 'Swift: strikes first',
  double: 'Twin: attacks twice',
  pierce: 'Pierce: ignores DEF',
  corrupt: 'Corrupt: infects on contact',
  aura: 'Field: hurts when adjacent',
  surge: 'Overflow: every 3rd blow x2',
};

// CRIT = % chance of a x2 hit. Each point of AGI above the attacker's adds 3% dodge.
const hitChances = (atk, def) => ({ crit: atk.crit / 100, miss: Math.min(0.4, Math.max(0.02, 0.04 + 0.03 * (def.agi - atk.agi))) });

// Expected HP lost fighting monster m, averaging in both sides' misses and crits.
// Infinity if the hero can't hurt it.
function battleCost(hero, m) {
  const hd = hero.atk - m.def;
  if (hd <= 0) return Infinity;
  const mine = hitChances(hero, m), theirs = hitChances(m, hero);
  const swings = Math.max(1, Math.ceil(m.hp / (hd * (1 - mine.miss) * (1 + mine.crit))));
  let hits = (swings - 1 + (m.swift ? 1 : 0)) * (m.double ? 2 : 1);
  if (m.surge) hits += Math.floor(hits / 3);
  const dmg = m.pierce ? m.atk : Math.max(0, m.atk - hero.def);
  return Math.round(hits * dmg * (1 - theirs.miss) * (1 + theirs.crit));
}

const HERO_START = { hp: 1000, atk: 10, def: 10, crit: 5, agi: 2, gold: 0, exp: 0, lv: 1, keys: { y: 1, b: 0, r: 0 } };
const expToNext = lv => 5 * lv * (lv + 1); // cumulative: 10, 30, 60, 100...
const levelGain = (lv, h) => ({ hp: Math.round(h.hp * 0.04 + 50), atk: Math.max(1, Math.round(h.atk * 0.02)), def: Math.max(1, Math.round(h.def * 0.02)), agi: lv % 3 === 0 ? 1 : 0 });
const fabricatorCost = n => 20 + 10 * n + 2 * n * n;
