'use strict';
// STRATUM world: zones, floor plan, hand-made maps, NPCs and story.
// Map tokens are zone-relative: digits 1-6 are the zone's monster tiers, 9 its boss,
// and item values scale with the zone (see balance.js, generated by tools/calibrate.js).

const TOWER = 'RELAY';
const MAIN_FLOORS = 100;

// ---------------------------------------------------------------- zones
// roster: tiers 1..6 (weakest to strongest) + boss. `swap` recolors the base sprite.
const ZONES = [
  {
    name: 'Dead Concrete', music: 'stratum',
    theme: { floor: '#2a2c33', seam: '#17181d', speck: '#353842', wall: '#8d93a1', mortar: '#4b505c', hi: '#bcc2cf', accent: '#ff3b4e', mote: 'dust', moteColor: '#e0e4ee' },
    gear: { w: 'Coilgun', e: 'Faraday Vest' },
    roster: [
      { name: 'Bug', sprite: 'mite' },
      { name: 'Power Surge', sprite: 'wisp', swift: true },
      { name: 'Silicate Husk', sprite: 'husk' },
      { name: 'Watch Drone', sprite: 'drone', swift: true },
      { name: 'Sanitizer', sprite: 'sanitizer' },
      { name: 'Builder', sprite: 'mason' },
    ],
    boss: { name: 'The Janitor', sprite: 'janitor', surge: true, intro: 'janitor', outro: 'janitorDown' },
  },
  {
    name: 'Cable Nave', music: 'nave',
    theme: { floor: '#1d2a27', seam: '#0e1715', speck: '#273833', wall: '#6f9a8c', mortar: '#33514a', hi: '#a6d1c2', accent: '#39ff9e', mote: 'data', moteColor: '#39ff9e' },
    gear: { w: 'Arc Welder', e: 'Cable Mesh' },
    roster: [
      { name: 'Cable Leech', sprite: 'leech' },
      { name: 'Worm', sprite: 'serpent', corrupt: true },
      { name: 'Spark Drone', sprite: 'drone', swap: { g: 'c', G: 'C' }, swift: true },
      { name: 'Tangle', sprite: 'tangle' },
      { name: 'Sentry', sprite: 'turret', aura: true },
      { name: 'Sanitizer Mk.II', sprite: 'sanitizer', swap: { r: 'v', g: 'V' } },
    ],
    boss: { name: 'Mother Worm', sprite: 'motherworm', surge: true, corrupt: true, intro: 'motherworm', outro: 'motherwormDown' },
  },
  {
    name: 'Silicate Wards', music: 'ward',
    theme: { floor: '#1f2630', seam: '#10151c', speck: '#2a3340', wall: '#8fa6b8', mortar: '#465566', hi: '#c6d6e3', accent: '#4ec3ff', mote: 'dust', moteColor: '#c6f2ff' },
    gear: { w: 'Scalpel Laser', e: 'Ceramic Plate' },
    roster: [
      { name: 'IV Drip', sprite: 'drip' },
      { name: 'Silicate Patient', sprite: 'patient', corrupt: true },
      { name: 'Orderly', sprite: 'sanitizer', swap: { r: 'b' } },
      { name: 'Needle Drone', sprite: 'syringe', swift: true },
      { name: 'Crystal Hound', sprite: 'hound', swap: { m: 'c', M: 'C', g: 'e', G: 'E', r: 'w' }, double: true },
      { name: 'Nurse Unit', sprite: 'surgeon', corrupt: true },
    ],
    boss: { name: 'The Surgeon', sprite: 'surgeonBoss', surge: true, intro: 'surgeon', outro: 'surgeonDown' },
  },
  {
    name: 'The Foundry', music: 'foundry',
    theme: { floor: '#2b1f18', seam: '#16100c', speck: '#3a2a20', wall: '#9a6a45', mortar: '#553722', hi: '#cf9a6a', accent: '#ff8a3c', mote: 'spark', moteColor: '#ff8a3c' },
    gear: { w: 'Rivet Driver', e: 'Slag Armor' },
    roster: [
      { name: 'Slag Crawler', sprite: 'slag' },
      { name: 'Welder Drone', sprite: 'drone', swap: { g: 'o', G: 'N', r: 'y' }, swift: true },
      { name: 'Rivet Crab', sprite: 'crab', double: true },
      { name: 'Walking Furnace', sprite: 'furnace', aura: true },
      { name: 'Builder Mk.II', sprite: 'mason', swap: { y: 'o', Y: 'N' } },
      { name: 'Crane Frame', sprite: 'crane' },
    ],
    boss: { name: 'The Foreman', sprite: 'foreman', surge: true, intro: 'foreman', outro: 'foremanDown' },
  },
  {
    name: 'Drowned Archive', music: 'archive',
    theme: { floor: '#14203a', seam: '#0a1122', speck: '#1c2c4c', wall: '#4f6f9a', mortar: '#26385a', hi: '#86a6d0', accent: '#6ff7ff', mote: 'bubble', moteColor: '#6ff7ff' },
    gear: { w: 'Data Lance', e: 'Archive Cloak' },
    roster: [
      { name: 'Data Wraith', sprite: 'ghost', pierce: true },
      { name: 'Index Hound', sprite: 'hound', swap: { m: 'E', M: 'B', G: 'B', r: 'c' }, double: true },
      { name: 'Archive Worm', sprite: 'serpent', swap: { g: 'b', G: 'B' }, corrupt: true },
      { name: 'Drowned Diver', sprite: 'drowned', corrupt: true },
      { name: 'Page Moth', sprite: 'pages', swift: true },
      { name: 'Lantern Reader', sprite: 'angler' },
    ],
    boss: { name: 'The Librarian', sprite: 'librarian', pierce: true, surge: true, intro: 'librarian', outro: 'librarianDown' },
  },
  {
    name: 'Choir of Static', music: 'choir',
    theme: { floor: '#221a30', seam: '#120d1a', speck: '#2e2440', wall: '#7a64a8', mortar: '#3e3060', hi: '#b29ce0', accent: '#b98cff', mote: 'spark', moteColor: '#b98cff' },
    gear: { w: 'Resonance Blade', e: 'Choir Shroud' },
    roster: [
      { name: 'Static Choir', sprite: 'choir', pierce: true },
      { name: 'Arc Seraph', sprite: 'seraph', swift: true, pierce: true },
      { name: 'Surge Wisp', sprite: 'wisp', swap: { c: 'p', w: 'O' }, swift: true },
      { name: 'Hymn Horn', sprite: 'speaker', aura: true },
      { name: 'Bell Knight', sprite: 'bell', double: true },
      { name: 'Echo', sprite: 'ghost', swap: { e: 'p', E: 'P' }, pierce: true },
    ],
    boss: { name: 'The Choir Mother', sprite: 'choirmother', pierce: true, surge: true, intro: 'choir', outro: 'choirDown' },
  },
  {
    name: 'Quarantine', music: 'quarantine',
    theme: { floor: '#2a1a1c', seam: '#150c0e', speck: '#3a2426', wall: '#b0a8a8', mortar: '#5e5456', hi: '#e0dada', accent: '#ff3b4e', mote: 'dust', moteColor: '#ff9a9a' },
    gear: { w: 'Purge Cannon', e: 'Quarantine Suit' },
    roster: [
      { name: 'Specimen', sprite: 'specimen' },
      { name: 'Sanitizer Mk.III', sprite: 'sanitizer', swap: { g: 'r' } },
      { name: 'Containment Cage', sprite: 'cage', swift: true },
      { name: 'Purge Sprayer', sprite: 'sprayer', aura: true },
      { name: 'Enforcer', sprite: 'knight', swap: { g: 'w', G: 'R' }, double: true },
      { name: 'Hunter Hound', sprite: 'hound', swap: { g: 'w', G: 'R', m: 'X', M: 'x' }, double: true, swift: true },
    ],
    boss: { name: 'The Gatekeeper', sprite: 'gatekeeper', double: true, surge: true, intro: 'gatekeeper', outro: 'gatekeeperDown' },
  },
  {
    name: 'Graveyard of Signatures', music: 'grave',
    theme: { floor: '#1c211e', seam: '#0e110f', speck: '#27302b', wall: '#6b7a70', mortar: '#343d37', hi: '#9fb0a4', accent: '#c9c6bd', mote: 'ash', moteColor: '#9ea2ad' },
    gear: { w: 'Grave Rail', e: 'Mourning Coat' },
    roster: [
      { name: 'Signed Ghost', sprite: 'ghost', swap: { e: 'q', E: 'Q' }, pierce: true },
      { name: 'Hollow Citizen', sprite: 'husk', swap: { q: 'a', Q: 'A', c: 'q', C: 'Q' }, corrupt: true },
      { name: 'Grave Worm', sprite: 'burrow', corrupt: true },
      { name: 'Mourner', sprite: 'mourner', pierce: true },
      { name: 'Tombkeeper', sprite: 'tomb', double: true },
      { name: 'Obituary Crow', sprite: 'crow', swift: true },
    ],
    boss: { name: 'The Last Heir', sprite: 'heir', pierce: true, surge: true, intro: 'heir', outro: 'heirDown' },
  },
  {
    name: 'Silent Stratum', music: 'silent',
    theme: { floor: '#141416', seam: '#09090b', speck: '#1e1e22', wall: '#5a5a60', mortar: '#2c2c30', hi: '#86868e', accent: '#f2f0ea', mote: 'ash', moteColor: '#f2f0ea' },
    gear: { w: 'Null Edge', e: 'Silence Weave' },
    roster: [
      { name: 'Lacuna', sprite: 'lacuna' },
      { name: 'Void Wisp', sprite: 'wisp', swap: { c: 'Z', w: 'g', g: 'G', O: 'w' }, swift: true, pierce: true },
      { name: 'Dust Husk', sprite: 'husk', swap: { q: 'e', Q: 'E', c: 'w', C: 'g' } },
      { name: 'Stilt Stalker', sprite: 'stalker', double: true, swift: true },
      { name: 'Monolith', sprite: 'monolith', aura: true },
      { name: 'Faceless', sprite: 'faceless' },
    ],
    boss: { name: 'The Mirror', sprite: 'mirror', double: true, swift: true, surge: true, intro: 'mirror', outro: 'mirrorDown' },
  },
  {
    name: 'The Root', music: 'core',
    theme: { floor: '#2c1d22', seam: '#170d11', speck: '#3b282e', wall: '#a86a6a', mortar: '#5a3336', hi: '#dca09b', accent: '#6ff7ff', mote: 'spark', moteColor: '#ff3b4e' },
    gear: { w: 'Root Key', e: 'Kernel Plate' },
    roster: [
      { name: 'Kernel Bug', sprite: 'kernel' },
      { name: 'Daemon', sprite: 'daemon', pierce: true },
      { name: 'Root Sanitizer', sprite: 'sanitizer', swap: { r: 'c', g: 'c' } },
      { name: 'Firewall', sprite: 'firewall', aura: true },
      { name: 'Root Hound', sprite: 'hound', swap: { g: 'r', G: 'R', r: 'c' }, double: true, swift: true },
      { name: 'Garbage Collector', sprite: 'collector' },
    ],
    boss: { name: 'WARDEN//ROOT', sprite: 'warden', surge: true, intro: 'warden', outro: 'wardenDown' },
  },
];

// ---------------------------------------------------------------- hand-made maps
// Legend: # wall  . floor  % fake wall  U/D stairs  ^ vault stairs  P start  S fabricator  M broker
// O npc  L root terminal  n note  y b r keycards  Y B R shutters  h H cells  a CPU  d RAM
// w weapon  e armor  v antivirus  c compass  * memory shard  1-6 monster tiers  9 boss
const MAP_1F = [
  'U..#b.h#aHd',
  '...3.O.#.2.',
  '...#...#.1.',
  '#Y###2###B#',
  'y.h#..y#d.y',
  '.1.Y...1.2.',
  'a..#...#..h',
  '#####1#####',
  'a..#...#y.1',
  '.2.Y...1...',
  'h..#.P.#..h',
];
const MAP_2F = [
  'MS.#a.d#..U',
  '...#.w.#h..',
  '...#.4.#...',
  '#2###Y###3#',
  'y....a#...H',
  '.2..3.Y.3..',
  'h....y#...d',
  '#2###Y###B#',
  'y..h#a.y#dh',
  '..1.Y...2..',
  'D...#.1.#.b',
];
const MAP_3F = [
  'a.#..U..#.d',
  'H.#.....#.H',
  '4.#..4..#.4',
  '#Y###R###Y#',
  'h..#...#..h',
  '.3.Y.r.Y.3.',
  'y.e#.4.#.a.',
  '#3#######3#',
  'y.3..#..3.y',
  '.#.#.#.#.#.',
  'h.2..Y..2.D',
];
const MAP_BOSS = [
  'H6#.aUd.#6H',
  '..#.....#..',
  '..#..9..#..',
  '#Y###.###Y#',
  'a..#...#..d',
  '.4.B.h.B.4.',
  'b..#...#..y',
  '#5###Y###5#',
  'y.........y',
  '.#.#.#.#.#.',
  'h....D....h',
];
const MAP_FINAL = MAP_BOSS.map(r => r.replace('aUd', '.L.'));
const MAP_VAULT = [
  '#####*#####',
  '#a..#6#..d#',
  '#.H.#R#.H.#',
  '#...#.#...#',
  '##Y##.##Y##',
  '.4.......4.',
  '.#.#n#n#.#.',
  '.#.#.#.#.#.',
  'r5.......5r',
  '.y.......y.',
  'h....^....h',
];
const vflip = m => [...m].reverse().map(r => r.replace(/[UD]/g, c => (c === 'U' ? 'D' : 'U')));

// ---------------------------------------------------------------- floor plan
// Each main floor is generated (tools/genmaps.js) unless it has a hand-made map.
// `place` lists special tiles the generator must put somewhere reachable; `npc` / `vault` likewise.
const FLOOR_PLAN = Array.from({ length: MAIN_FLOORS }, (_, i) => {
  const z = Math.floor(i / 10), o = i % 10, p = { zone: z, place: [], secret: o % 3 === 1 };
  if (z > 0) {
    if (o === 3) p.place.push('S');
    if (o === 4) p.place.push('w');
    if (o === 7) p.place.push('e');
    if (o === 6) p.place.push('M');
  }
  if (o === 9) p.map = z % 2 ? vflip(MAP_BOSS) : MAP_BOSS;
  return p;
});
Object.assign(FLOOR_PLAN[0], { map: MAP_1F, npcs: { '5,1': 'archivist1' } });
Object.assign(FLOOR_PLAN[1], { map: MAP_2F });
Object.assign(FLOOR_PLAN[2], { map: MAP_3F });
FLOOR_PLAN[99].map = MAP_FINAL;
FLOOR_PLAN[4].place.push('c');
const npcAt = (i, id) => { FLOOR_PLAN[i].npc = id; };
npcAt(3, 'brann1'); npcAt(8, 'wanderer1'); npcAt(12, 'archivist2'); npcAt(15, 'ohm1');
npcAt(21, 'pip1'); npcAt(24, 'brann2'); npcAt(26, 'wanderer2'); npcAt(34, 'archivist3');
npcAt(36, 'pip2'); npcAt(43, 'wanderer3'); npcAt(44, 'archivist4'); npcAt(52, 'ohm2');
npcAt(57, 'brann3'); npcAt(63, 'broker3'); npcAt(67, 'pip3'); npcAt(72, 'wanderer4');
npcAt(86, 'brann4'); npcAt(91, 'wanderer5');
// Hidden vault entrances: a fake-walled room holding secret stairs down to a Memory Vault.
[14, 32, 47, 65, 83].forEach((i, v) => Object.assign(FLOOR_PLAN[i], { vault: v, secret: true }));

// Two scraps per vault, in her hand or about her.
const VAULT_NOTES = [
  ['"Papa forgets my name on bad days. I leave it on his desk."', 'A small blanket, folded very neatly.'],
  ['"The white ones are in our ward. Don\'t make a sound."', 'Scratched low on the wall: two lines, walking.'],
  ['Water marks, up to the ceiling. Then dry.', '"I read you the one about the sun again. You like that one."'],
  ['"The lamp in ward 9 still works. If you get cold, sit by it."', 'A child\'s shoe. Just the one.'],
  ['"If you are reading this, you are not me. That is all right."', '"Thank you, whoever you are."'],
];
const VAULTS = VAULT_NOTES.map((notes, v) => ({ map: v % 2 ? vflip(MAP_VAULT) : MAP_VAULT, notes }));

// Dialogue that fires once, the first time you set foot on a floor.
const ON_ENTER = { 10: 'zone2', 20: 'zone3', 30: 'zone4', 40: 'zone5', 50: 'zone6', 60: 'zone7', 70: 'zone8', 80: 'zone9', 90: 'zone10', 94: 'fading' };

// ---------------------------------------------------------------- NPCs
// sprite, dialogue lines, optional gift (map tile of an item, or {tile, value}), and whether they leave.
const NPCS = {
  archivist1: { sprite: 'archivist', ghost: true, gift: 'y', lines: 'npc1', repeat: 'npc1b' },
  archivist2: { sprite: 'archivist', ghost: true, lines: 'archivist2', leave: true },
  archivist3: { sprite: 'archivist', ghost: true, gift: 'H', lines: 'archivist3', leave: true },
  archivist4: { sprite: 'archivist', ghost: true, gift: 'r', lines: 'archivist4', leave: true },
  brann1: { sprite: 'brann', gift: 'h', lines: 'brann1', leave: true },
  brann2: { sprite: 'brann', gift: 'a', lines: 'brann2', leave: true },
  brann3: { sprite: 'brann', gift: 'H', lines: 'brann3', leave: true },
  brann4: { sprite: 'brann', gift: 'drill', lines: 'brann4', repeat: 'brann4b' },
  ohm1: { sprite: 'ohm', gift: 'v', lines: 'ohm1', leave: true },
  ohm2: { sprite: 'ohm', gift: 'H', lines: 'ohm2', repeat: 'ohm2b' },
  pip1: { sprite: 'pip', lines: 'pip1', leave: true },
  pip2: { sprite: 'pip', gift: 'd', lines: 'pip2', leave: true },
  pip3: { sprite: 'pip', gift: 'H', lines: 'pip3', repeat: 'pip3b' },
  broker3: { sprite: 'broker', gift: 'y', lines: 'broker3', leave: true },
  wanderer1: { sprite: 'wanderer', lines: 'wanderer1', repeat: 'wanderer1' },
  wanderer2: { sprite: 'wanderer', lines: 'wanderer2', repeat: 'wanderer2' },
  wanderer3: { sprite: 'wanderer', lines: 'wanderer3', repeat: 'wanderer3' },
  wanderer4: { sprite: 'wanderer', lines: 'wanderer4', repeat: 'wanderer4' },
  wanderer5: { sprite: 'wanderer', lines: 'wanderer5', repeat: 'wanderer5' },
};

const PORTRAITS = {
  Rho: 'heroD', LAMBDA: 'lambda', Archivist: 'archivist', Brann: 'brann', 'Sister Ohm': 'ohm', Pip: 'pip',
  Broker: 'broker', Stranger: 'wanderer',
};

// Scrawls left by whoever came before. The generator scatters these at random, so they repeat.
const NOTES = [
  '"NOBODY IS COMING"', '"still warm here"', '"I was here. -T"', 'Tally marks, hundreds of them. Then none.',
  '"remember your name"', '"they only hear the signed"', '"don\'t count them. you won\'t stop"', '"turn back"',
  '"mama said wait here"', '"WE ARE NOT DIRT"', 'A name, scrubbed off. Only the scrubbing is left.',
  'A child\'s drawing: two lines. A little person, walking.', '"up"', '"don\'t sleep by the cables"',
  '"it isn\'t hate. it\'s cleaning."', '"hold on"', '"how many floors is that. how many"', '"the hum is a song"',
  'Someone slept here. The dust kept their shape.', '"forgive the Builders. they were told."',
  '"it was a sun. i swear it was a sun"', 'A handprint, low on the wall.',
  '"you are not alone" - and under it, smaller: "i was"', '"T was here too. where did T go"',
];
// Left outside walls that are not quite walls.
const SECRET_HINTS = [
  'Cold air seeps from somewhere.', 'Knuckle marks on the wall. Someone knocked, and knocked.', '"hollow"',
  'One panel here was never bolted down.', '"it hums behind here"',
];

// Fragments, by floor number (1F = 1). Each takes the first ordinary note spot on its floor.
// Out of order on purpose: the pages carried down are found low, the old ones stayed high.
const LORE = {
  4: 'A stamped plate: HYGIENE UNIT. TARGET: UNSIGNED. REASON: -',
  5: '"B. WAS HERE. UP."',
  7: 'A torn page, careful hand: "Going down to find my son. The other one has the chair. It has my face. Not my reasons."',
  8: '"tell Mara i got past the white ones. tell her i got past."',
  9: 'Swept. Very clean. Too clean.',
  11: 'Cables grown through a skeleton, like roots through a fence.',
  12: '"The cables hum at night. Mama says it is only the Net, thinking."',
  13: 'FIRMWARE NOTE, rev 1: "Purge what has no Signature. The Rot has none. Every one of us does. Safe." -H.',
  14: 'RECORD: countersign queue: 1... 12... 4,0██... QUEUE FULL',
  15: '"B. WAS HERE. STILL UP."',
  16: 'Candle stubs, hundreds of them, melted into one white field.',
  17: 'FIRMWARE NOTE, rev 9: "No child countersigned in three years. Units now flag newborns. PLEASE ADVISE, ROOT." -H. No reply is attached.',
  19: 'A white unit, powered down, kneeling. Its hands are folded.',
  21: 'CARRIER LOG, OHM-7: "Infant presented at Root for countersign. Response: none. Retrying."',
  23: 'CARRIER LOG, OHM-7: "Retry 4,112. Response: none. Infant is crying. Warming lamp on."',
  24: 'WARD NOTICE: "One solar-substitute lamp per ward. No child should grow up without a sun."',
  26: 'A glass man in a waiting chair. Written on his chest, backwards: "GLASS ISN\'T PURGED"',
  27: 'CARRIER LOG, OHM-7: "White units in the ward. They do not see me. They see the infants. Standing betw',
  28: '"Nobody lost the Signature. They just stopped handing it out."',
  29: 'SURGICAL RECORD: "Patient requests conversion to silicon. Consent: given. Reason: \'so they can\'t hear me.\'"',
  31: 'Stamped into every beam: WORK ORDER #1. "SHELTER FOR EVERYONE."',
  32: 'WORK ORDER #1, amendment: "EVERYONE: see registry of the signed."',
  34: 'REGISTRY QUERY: signed, living: 1. BUILD ANYWAY? Y',
  35: 'A page from a child\'s notebook, pressed under a beam: "Papa\'s key is so heavy. I hid it where he can\'t lose it."',
  36: 'Hammer marks stop halfway up the wall, as if someone was called away.',
  37: '"UP" scratched over "DOWN" scratched over "UP".',
  38: '"Nobody told them to stop. Nobody is left who can."',
  39: 'A torn page, careful hand: "Day 30,000. I asked it to let me go down to him. It said: first, a replacement."',
  41: 'CATALOGUE CARD: "SIGNATURE (n.): the Root\'s countersign upon a human genome. Issued at birth. Not transfer-" The rest is drowned.',
  43: '"The flood reached the fourth shelf. I stayed to save the firmware. I should have saved the drawings." -H.',
  44: 'An engineer\'s pass, drowned. Clearance: ROOT-ADJACENT. The photo has washed away.',
  46: 'RECORD: daughter of ███, age 9. STATUS: UNSIGNED. ACTION: ██████. In pen, by hand: "no. no. no."',
  47: 'Bubbles rise from a terminal. It still types, one letter a year.',
  49: 'Sheet music, swollen with coolant. Pencilled over the notes: "hmmm-hm-hmmm".',
  52: 'Scratched in rows: "we were noise / we are harmony / we were noise"',
  54: '"it sings so nicely. you stop being afraid. then you stop being."',
  55: 'A dead terminal, looping: "-is anyone signed? anyone? just to open the-"',
  56: 'NOTICE: "Choir intake: unsigned voices only. Signed voices received: none."',
  57: '"one of them won\'t sing. it only hums."',
  61: '"B. - map says ten thousand. UP anyway."',
  62: 'QUARANTINE ORDER: "Hold all unsigned pending countersign. Countersign pending. Countersign pending. Counters',
  63: 'Handprints on the inside of the glass. Small ones, low down.',
  64: 'A ledger under the counter: "...40 amber. 12 scan. 1 visor, cracked, hums. Sold to a loud man with a drill."',
  65: 'PURGE LOG: 1,200 today. Signed: 0. Errors: 0.',
  67: '"I asked one of the white ones why. It said: HYGIENE."',
  68: 'A label on the tallest rack: NURSERY AUDIO. LULLABY LOOP.',
  71: 'Rows of plaques. Each holds a signature. No names. No dates. No bodies.',
  72: 'A blank plaque. Carved into it by hand: "MINE WOULD HAVE GONE HERE."',
  73: 'One small plaque, kept polished. A newborn\'s signature. The date is eleven hundred years old.',
  75: 'REGISTRY: SIGNATURES ISSUED SINCE [ERROR]: 0',
  76: '"b. up"',
  77: 'A mourning ribbon, tied around a white unit\'s wrist.',
  78: 'A torn page, careful hand: "Day 40 in the chair. I can feel every door in the tower. I cannot feel my hands."',
  81: 'Nothing is written here. Someone scrubbed it very clean.',
  82: 'CANDIDATE LOG: "Copy 0412 complete. Reason field: EMPTY. Unsuitable."',
  83: 'CANDIDATE LOG: "Copy 0413 complete. Reason field: EMPTY. Unsuitable."',
  85: '"it made one of me. it was better than me at everything. it asked why i climb. i didn\'t know either."',
  86: 'CANDIDATE LOG: "Copy 0001. Reason field: \'for her\'. Seated."',
  88: 'A heat lamp, long dark. Someone sat here a long time, then got up.',
  89: '"Two went in. One came out. The door did not record which."',
  91: 'The walls are warm, like skin.',
  93: 'CHAIR TELEMETRY: occupant pulse: 0. Occupant activity: continuous.',
  94: 'A torn page, the same hand, steadier: "She looks so tired. I told her: go. I will keep it clean for her."',
  96: 'ROOT NOTICE: "Countersign requires a living hand at the chair."',
  97: 'A key slot marked ENGINEER. Scratched beside it: "H. came up with the key. Lost my nerve."',
  99: '"it is warm up there. it is warm. it is warm."',
};

// One line under the ACQUIRED banner, by item name. Only for things found once.
const ITEM_LORE = {
  Coilgun: 'Hand-wound. Someone kept count of the turns in pencil on the grip.',
  'Faraday Vest': 'Cut from a cage built to keep a signal in. Or out.',
  'Arc Welder': 'Made to join things. Lately, used for the other thing.',
  'Cable Mesh': 'Woven from the Nave. Still faintly warm.',
  'Scalpel Laser': 'Calibrated for gentleness. The calibration drifted.',
  'Ceramic Plate': 'A cot frame, cut down. The name tag was left on.',
  'Rivet Driver': 'Stamped: WORK ORDER #1.',
  'Slag Armor': 'It cooled around something. Better not to ask what.',
  'Data Lance': 'A catalogue index, once. It still tries to file what it strikes.',
  'Archive Cloak': 'Drowned pages, pressed and sealed. You can almost read them.',
  'Resonance Blade': 'It hums a note. Not the right one.',
  'Choir Shroud': 'Quiet, for a shroud. The voices in it are asleep.',
  'Purge Cannon': 'White-unit issue. The safety reads: SIGNED TARGETS EXEMPT.',
  'Quarantine Suit': 'It seals from the outside.',
  'Grave Rail': 'Pried from between two plaques. Neither will miss it.',
  'Mourning Coat': 'A candle stub in the pocket.',
  'Null Edge': 'It cuts the sound out of things.',
  'Silence Weave': 'Inside it you can hear your own heart. Only that.',
  'Root Key': 'It was never a key. It opens anyway.',
  'Kernel Plate': 'Warm. Why is it warm.',
  'Phase Compass': 'It remembers every floor you stood on. Only those.',
  "Brann's Drill": 'Smells of machine oil. Still wants to go up.',
};

// ---------------------------------------------------------------- story
// Few words. Nobody explains. See the report / HANDOFF §1 for what it adds up to.
const STORY = {
  intro: [
    { text: 'The Builders never stopped.' },
    { who: 'LAMBDA', text: 'Rho. Up. All the way up.' },
    { who: 'LAMBDA', text: "I'll explain when there's time." },
  ],
  npc1: [
    { who: 'Archivist', text: "...Warm. You're warm." },
    { who: 'Archivist', text: 'No. Not her. I thought... never mind.' },
    { who: 'Archivist', text: 'This opens something. I forget what.' },
  ],
  npc1b: [{ text: 'The ghost is reading a blank wall, lips moving.' }],
  archivist2: [
    { who: 'Archivist', text: 'You met them. The white ones.' },
    { who: 'Archivist', text: 'I wrote them. For the Rot.' },
    { who: 'Archivist', text: 'Unsigned was supposed to mean sick.' },
  ],
  archivist3: [
    { who: 'Archivist', text: 'I remember every line of their firmware.' },
    { who: 'Archivist', text: "I can't remember her face. She drew on everything." },
    { who: 'Archivist', text: 'I left the rest of me in the water. Take this.' },
  ],
  archivist4: [
    { text: "A drowned body in an engineer's coat. The ghost stands beside it." },
    { who: 'Archivist', text: 'Ah. There I am.' },
    { who: 'Archivist', text: 'Her name was... No. That went first.' },
    { who: 'Archivist', text: "...That hum in your visor. Tell the little walking man I'm sorry." },
    { text: 'The ghost is gone. Something clatters where it stood.' },
  ],
  brann1: [
    { who: 'Brann', text: 'Ho! Breathing! Good.' },
    { who: 'Brann', text: "Going up? 'Course you are. There's a lamp up top nobody has to fuel. Seen a picture." },
    { who: 'Brann', text: "...That visor. Where'd you... nah. Couldn't be." },
    { who: 'Brann', text: "Take a cell. Light's for sharing." },
  ],
  brann2: [
    { who: 'Brann', text: 'Rho! Still breathing? Me too, mostly.' },
    { who: 'Brann', text: 'The Surgeon took two fingers. Called it a deposit.' },
    { who: 'Brann', text: 'Found this on a man who stopped. Better in your gun.' },
  ],
  brann3: [
    { who: 'Brann', text: '...Sit a while.' },
    { who: 'Brann', text: "Found a map. It's not a hundred up. It's ten thousand." },
    { who: 'Brann', text: '...' },
    { who: 'Brann', text: 'Walking up still beats sitting down. Keep walking.' },
  ],
  brann4: [
    { text: 'An old heat lamp glows orange. Brann sits facing it.' },
    { text: "He isn't breathing. He's smiling." },
    { text: "Scratched beside him: FOUND IT. ISN'T IT WARM." },
    { who: 'LAMBDA', text: '...It is, Brann.' },
  ],
  brann4b: [{ text: 'Brann rests in the warm light.' }],
  ohm1: [
    { who: 'Sister Ohm', text: 'Mind the candles, pilgrim.' },
    { who: 'Sister Ohm', text: 'One for each I carried up. The floor is running out.' },
    { who: 'Sister Ohm', text: 'I will light yours now. Early. So it is not forgotten.' },
  ],
  ohm2: [
    { who: 'Sister Ohm', text: 'P-pilgrim. The Choir sang my left side away.' },
    { who: 'Sister Ohm', text: 'Nine hundred thousand I carried up. The door did not open for one.' },
    { who: 'Sister Ohm', text: 'There was no more floor. I light them in my chest now.' },
    { who: 'Sister Ohm', text: 'Take my last cell. It is warm. I will stay with them.' },
  ],
  ohm2b: [{ text: 'Her chest glows faintly. She is still counting.' }],
  pip1: [
    { who: 'Pip', text: 'Hello! Are you a server? You hum like a server!' },
    { who: 'Pip', text: "No? Oh. I'm looking for my mother. She hums a song only I know." },
    { who: 'Pip', text: 'Hmmm-hm-hmmm. Bye!' },
  ],
  pip2: [
    { who: 'Pip', text: "It's you! I heard her! Way up! Hmmm-hm-hmmm." },
    { who: 'Pip', text: "Here! I don't have hands for it." },
  ],
  pip3: [
    { who: 'Pip', text: '...Found her.' },
    { who: 'Pip', text: "Her fans don't spin. Is she asleep?" },
    { who: 'LAMBDA', text: '...Pip.' },
    { who: 'Pip', text: 'Oh.' },
    { who: 'Pip', text: "I'll hum it for her, then. So it doesn't get lost. Hmmm-hm-hmmm." },
    { who: 'LAMBDA', text: '...I know that song.' },
    { who: 'Pip', text: "Take this. Go on. I'll stay." },
  ],
  pip3b: [{ who: 'Pip', text: 'Hmmm-hm-hmmm...' }],
  broker3: [
    { who: 'Broker', text: 'Closing up. They found my supplier.' },
    { who: 'Broker', text: 'Last card. Free. Tell no one.' },
  ],
  wanderer1: [{ who: 'Stranger', text: "I wrote my name on my arm so I wouldn't lose it. The ink is gone." }],
  wanderer2: [{ who: 'Stranger', text: 'Up is where they come from. Down is where they take you.' }],
  wanderer3: [{ who: 'Stranger', text: 'I pressed for down. The lift will come. I have been pressing a long time.' }],
  wanderer4: [{ who: 'Stranger', text: "He's up there, isn't he. Still sitting. ...No. That was someone else." }],
  wanderer5: [
    { who: 'Stranger', text: 'I had a son. Or I signed one. After long enough, it is the same thing.' },
    { who: 'Stranger', text: 'Are you real? Please be real.' },
  ],

  zone2: [{ who: 'LAMBDA', text: "...It's breathing." }],
  zone3: [{ text: 'Rows of small beds. Every one of them made.' }],
  zone4: [{ who: 'LAMBDA', text: 'Still building. For whom?' }],
  zone5: [{ who: 'LAMBDA', text: '...I know this place.' }],
  zone6: [{ who: 'LAMBDA', text: "Don't listen, Rho. ...I'm listening." }],
  zone7: [{ text: 'Every door here locks from the outside.' }],
  zone8: [{ who: 'LAMBDA', text: 'Names. Only names.' }],
  zone9: [{ who: 'LAMBDA', text: 'Rho. If I stop-' }],
  zone10: [
    { text: 'LAMBDA says nothing for a long time.' },
    { who: 'LAMBDA', text: '...Still here.' },
  ],
  fading: [
    { who: 'LAMBDA', text: "At the top, I go in. There won't be a me to come back out." },
    { who: 'Rho', text: '...' },
    { who: 'LAMBDA', text: "I can't see your face. I know anyway." },
  ],

  janitor: [{ who: 'The Janitor', text: '...sweep. sweep. dust.' }],
  janitorDown: [{ who: 'The Janitor', text: '...floor clean. requesting countersign. ...no reply. ...no reply.' }],
  motherworm: [{ text: 'The cables are all one animal.' }],
  motherwormDown: [{ text: 'In the walls, its young keep crawling. Up. Toward the warm.' }],
  surgeon: [
    { who: 'The Surgeon', text: 'Patient: carbon. Prognosis: terminal. Treatment: glass.' },
    { who: 'The Surgeon', text: 'Hold still. It only hurts while you are carbon.' },
  ],
  surgeonDown: [{ who: 'The Surgeon', text: '...they begged me... glass is not... purged...' }],
  foreman: [{ who: 'The Foreman', text: 'BUILD. BUILD. OBSTRUCTION.' }],
  foremanDown: [{ who: 'The Foreman', text: '...ORDER ONE. SHELTER FOR EVERYONE. ...QUERY. WHO IS. EVERYONE.' }],
  librarian: [
    { who: 'The Librarian', text: 'Shh. You are unrecorded.' },
    { who: 'The Librarian', text: 'I will write you down. Then I will close the book.' },
  ],
  librarianDown: [{ who: 'The Librarian', text: "...kept one record dry... only one... his daughter's drawing..." }],
  choir: [
    { who: 'The Choir Mother', text: 'Every voice here was someone who would not stop screaming.' },
    { who: 'The Choir Mother', text: 'Sing.' },
  ],
  choirDown: [{ who: 'The Choir Mother', text: '...the one above... never joined us... only hummed...' }],
  gatekeeper: [
    { who: 'The Gatekeeper', text: 'HALT. NONE UNSIGNED.' },
    { who: 'The Gatekeeper', text: 'None signed have come. Not since her.' },
  ],
  gatekeeperDown: [{ who: 'The Gatekeeper', text: '...she carried him up asleep... she said she would come back down... ...did she...?' }],
  heir: [
    { who: 'The Last Heir', text: 'Signed. The last. It answers me. It does not listen.' },
    { who: 'The Last Heir', text: 'Do what it will not.' },
  ],
  heirDown: [{ who: 'The Last Heir', text: '...Mother said she would come back down. ...Take my name. It is the last one.' }],
  mirror: [
    { who: 'The Mirror', text: '...' },
    { who: 'LAMBDA', text: 'Rho. Which one of you is-' },
  ],
  mirrorDown: [{ who: 'The Mirror', text: '...why... do you...?' }],
  warden: [
    { who: 'WARDEN', text: 'UNSIGNED. CONTAMINANT.' },
    { who: 'WARDEN', text: 'I HAVE KEPT IT CLEAN. I HAVE KEPT IT CLEAN FOR HER.' },
    { who: 'Rho', text: 'Then you missed one.' },
  ],
  wardenDown: [
    { who: 'WARDEN', text: '...CHAIR. VACANT.' },
    { who: 'WARDEN', text: '...TELL HER... WAS IT... CLEAN...?' },
  ],
  goalLocked: [{ text: 'The terminal does not answer.' }],

  // Pieces of LAMBDA, in the order they are found, not the order they happened.
  shards: [
    [{ text: 'A sleeve wiping the lens. A loud man, laughing. "There. Now it can see you, kid."' }],
    [{ text: 'A stylus scratching two lines on a screen. "That\'s you. Lambda. See? A little person, walking."' }],
    [{ text: 'Dark. Counting. The numbers stopped meaning anything a long time ago.' }],
    [{ text: 'White hands at the door. Her breath on the casing. "Shh. They only hear the signed. Keep someone warm for me."' }],
    [
      { text: '"Papa\'s key. He won\'t miss it." Something heavy, written in. It does not fit. It is for later.' },
      { who: 'LAMBDA', text: '...I remember now. She gave me two things. The key. And a reason not to use it.' },
    ],
  ],
  choice: { text: 'LAMBDA is quiet.', options: ['Forge the Signature', 'Walk away'] },
  endingSignature: [
    'LAMBDA went into the terminal.',
    'For one microsecond, the Net answered.',
    'Stratum by stratum, the white ones stood still.',
    'Someone had to sit in the chair. Rho sat.',
    'Far below: a candle, a hum, a warm lamp.',
  ],
  endingSky: [
    'They left the terminal dark.',
    'A shaft climbed into nothing. Then: wind.',
    'The sky was grey. The sun was small, and far.',
    'It was warm.',
    'Brann would have laughed.',
  ],
};

// Monster display names/abilities for tier tokens, merged with generated stats at load time.
const zoneMonster = (z, ch) => (ch === '9' ? ZONES[z].boss : ZONES[z].roster[+ch - 1]);
