'use strict';
// STRATUM world: zones, floor plan, hand-made maps, NPCs and story.
// Map tokens are zone-relative: digits 1-6 are the zone's monster tiers, 9 its boss,
// and item values scale with the zone (see balance.js, generated by tools/calibrate.js).

const TOWER = 'RELAY';
const MAIN_FLOORS = 100;

// ---------------------------------------------------------------- zones
// roster: tiers 1..6 (weakest to strongest) + boss. `swap` recolors the base sprite.
const ZONES = [
  {
    name: 'Dead Concrete', music: 'stratum',
    theme: { floor: '#2a2c33', seam: '#17181d', speck: '#353842', wall: '#8d93a1', mortar: '#4b505c', hi: '#bcc2cf', accent: '#ff3b4e', mote: 'dust', moteColor: '#e0e4ee' },
    gear: { w: 'Coilgun', e: 'Faraday Vest' },
    roster: [
      { name: 'Bug', sprite: 'mite' },
      { name: 'Power Surge', sprite: 'wisp', swift: true },
      { name: 'Silicate Husk', sprite: 'husk' },
      { name: 'Watch Drone', sprite: 'drone', swift: true },
      { name: 'Sanitizer', sprite: 'sanitizer' },
      { name: 'Builder', sprite: 'mason' },
    ],
    boss: { name: 'The Janitor', sprite: 'janitor', surge: true, intro: 'janitor', outro: 'janitorDown' },
  },
  {
    name: 'Cable Nave', music: 'nave',
    theme: { floor: '#1d2a27', seam: '#0e1715', speck: '#273833', wall: '#6f9a8c', mortar: '#33514a', hi: '#a6d1c2', accent: '#39ff9e', mote: 'data', moteColor: '#39ff9e' },
    gear: { w: 'Arc Welder', e: 'Cable Mesh' },
    roster: [
      { name: 'Cable Leech', sprite: 'leech' },
      { name: 'Worm', sprite: 'serpent', corrupt: true },
      { name: 'Spark Drone', sprite: 'drone', swap: { g: 'c', G: 'C' }, swift: true },
      { name: 'Tangle', sprite: 'tangle' },
      { name: 'Sentry', sprite: 'turret', aura: true },
      { name: 'Sanitizer Mk.II', sprite: 'sanitizer', swap: { r: 'v', g: 'V' } },
    ],
    boss: { name: 'Mother Worm', sprite: 'motherworm', surge: true, corrupt: true, intro: 'motherworm', outro: 'motherwormDown' },
  },
  {
    name: 'Silicate Wards', music: 'ward',
    theme: { floor: '#1f2630', seam: '#10151c', speck: '#2a3340', wall: '#8fa6b8', mortar: '#465566', hi: '#c6d6e3', accent: '#4ec3ff', mote: 'dust', moteColor: '#c6f2ff' },
    gear: { w: 'Scalpel Laser', e: 'Ceramic Plate' },
    roster: [
      { name: 'IV Drip', sprite: 'drip' },
      { name: 'Silicate Patient', sprite: 'patient', corrupt: true },
      { name: 'Orderly', sprite: 'sanitizer', swap: { r: 'b' } },
      { name: 'Needle Drone', sprite: 'syringe', swift: true },
      { name: 'Crystal Hound', sprite: 'hound', swap: { g: 'c', G: 'C', r: 'w' }, double: true },
      { name: 'Nurse Unit', sprite: 'surgeon', corrupt: true },
    ],
    boss: { name: 'The Surgeon', sprite: 'surgeonBoss', surge: true, intro: 'surgeon', outro: 'surgeonDown' },
  },
  {
    name: 'The Foundry', music: 'foundry',
    theme: { floor: '#2b1f18', seam: '#16100c', speck: '#3a2a20', wall: '#9a6a45', mortar: '#553722', hi: '#cf9a6a', accent: '#ff8a3c', mote: 'spark', moteColor: '#ff8a3c' },
    gear: { w: 'Rivet Driver', e: 'Slag Armor' },
    roster: [
      { name: 'Slag Crawler', sprite: 'slag' },
      { name: 'Welder Drone', sprite: 'drone', swap: { g: 'o', G: 'N', r: 'y' }, swift: true },
      { name: 'Rivet Crab', sprite: 'crab', double: true },
      { name: 'Walking Furnace', sprite: 'furnace', aura: true },
      { name: 'Builder Mk.II', sprite: 'mason', swap: { y: 'o' } },
      { name: 'Crane Frame', sprite: 'crane' },
    ],
    boss: { name: 'The Foreman', sprite: 'foreman', surge: true, intro: 'foreman', outro: 'foremanDown' },
  },
  {
    name: 'Drowned Archive', music: 'archive',
    theme: { floor: '#14203a', seam: '#0a1122', speck: '#1c2c4c', wall: '#4f6f9a', mortar: '#26385a', hi: '#86a6d0', accent: '#6ff7ff', mote: 'bubble', moteColor: '#6ff7ff' },
    gear: { w: 'Data Lance', e: 'Archive Cloak' },
    roster: [
      { name: 'Data Wraith', sprite: 'ghost', pierce: true },
      { name: 'Index Hound', sprite: 'hound', swap: { g: 'b', G: 'B', r: 'c' }, double: true },
      { name: 'Archive Worm', sprite: 'serpent', swap: { g: 'b', G: 'B' }, corrupt: true },
      { name: 'Drowned Diver', sprite: 'drowned', corrupt: true },
      { name: 'Page Moth', sprite: 'pages', swift: true },
      { name: 'Lantern Reader', sprite: 'angler' },
    ],
    boss: { name: 'The Librarian', sprite: 'librarian', pierce: true, surge: true, intro: 'librarian', outro: 'librarianDown' },
  },
  {
    name: 'Choir of Static', music: 'choir',
    theme: { floor: '#221a30', seam: '#120d1a', speck: '#2e2440', wall: '#7a64a8', mortar: '#3e3060', hi: '#b29ce0', accent: '#b98cff', mote: 'spark', moteColor: '#b98cff' },
    gear: { w: 'Resonance Blade', e: 'Choir Shroud' },
    roster: [
      { name: 'Static Choir', sprite: 'choir', pierce: true },
      { name: 'Arc Seraph', sprite: 'seraph', swift: true, pierce: true },
      { name: 'Surge Wisp', sprite: 'wisp', swap: { c: 'p', w: 'O' }, swift: true },
      { name: 'Hymn Horn', sprite: 'speaker', aura: true },
      { name: 'Bell Knight', sprite: 'bell', double: true },
      { name: 'Echo', sprite: 'ghost', swap: { e: 'p', E: 'P' }, pierce: true },
    ],
    boss: { name: 'The Choir Mother', sprite: 'choirmother', pierce: true, surge: true, intro: 'choir', outro: 'choirDown' },
  },
  {
    name: 'Quarantine', music: 'quarantine',
    theme: { floor: '#2a1a1c', seam: '#150c0e', speck: '#3a2426', wall: '#b0a8a8', mortar: '#5e5456', hi: '#e0dada', accent: '#ff3b4e', mote: 'dust', moteColor: '#ff9a9a' },
    gear: { w: 'Purge Cannon', e: 'Quarantine Suit' },
    roster: [
      { name: 'Specimen', sprite: 'specimen' },
      { name: 'Sanitizer Mk.III', sprite: 'sanitizer', swap: { g: 'r' } },
      { name: 'Containment Cage', sprite: 'cage', swift: true },
      { name: 'Purge Sprayer', sprite: 'sprayer', aura: true },
      { name: 'Enforcer', sprite: 'knight', swap: { g: 'w', G: 'R' }, double: true },
      { name: 'Hunter Hound', sprite: 'hound', swap: { g: 'w', G: 'R' }, double: true, swift: true },
    ],
    boss: { name: 'The Gatekeeper', sprite: 'gatekeeper', double: true, surge: true, intro: 'gatekeeper', outro: 'gatekeeperDown' },
  },
  {
    name: 'Graveyard of Signatures', music: 'grave',
    theme: { floor: '#1c211e', seam: '#0e110f', speck: '#27302b', wall: '#6b7a70', mortar: '#343d37', hi: '#9fb0a4', accent: '#c9c6bd', mote: 'ash', moteColor: '#9ea2ad' },
    gear: { w: 'Grave Rail', e: 'Mourning Coat' },
    roster: [
      { name: 'Signed Ghost', sprite: 'ghost', swap: { e: 'q', E: 'Q' }, pierce: true },
      { name: 'Hollow Citizen', sprite: 'husk', swap: { q: 'g', Q: 'G', c: 'q' }, corrupt: true },
      { name: 'Grave Worm', sprite: 'burrow', corrupt: true },
      { name: 'Mourner', sprite: 'mourner', pierce: true },
      { name: 'Tombkeeper', sprite: 'tomb', double: true },
      { name: 'Obituary Crow', sprite: 'crow', swift: true },
    ],
    boss: { name: 'The Last Heir', sprite: 'heir', pierce: true, surge: true, intro: 'heir', outro: 'heirDown' },
  },
  {
    name: 'Silent Stratum', music: 'silent',
    theme: { floor: '#141416', seam: '#09090b', speck: '#1e1e22', wall: '#5a5a60', mortar: '#2c2c30', hi: '#86868e', accent: '#f2f0ea', mote: 'ash', moteColor: '#f2f0ea' },
    gear: { w: 'Null Edge', e: 'Silence Weave' },
    roster: [
      { name: 'Lacuna', sprite: 'lacuna' },
      { name: 'Void Wisp', sprite: 'wisp', swap: { c: 'Z', w: 'g', O: 'w' }, swift: true, pierce: true },
      { name: 'Dust Husk', sprite: 'husk', swap: { q: 'e', Q: 'E', c: 'w' } },
      { name: 'Stilt Stalker', sprite: 'stalker', double: true, swift: true },
      { name: 'Monolith', sprite: 'monolith', aura: true },
      { name: 'Faceless', sprite: 'faceless' },
    ],
    boss: { name: 'The Mirror', sprite: 'mirror', double: true, swift: true, surge: true, intro: 'mirror', outro: 'mirrorDown' },
  },
  {
    name: 'The Root', music: 'core',
    theme: { floor: '#2c1d22', seam: '#170d11', speck: '#3b282e', wall: '#a86a6a', mortar: '#5a3336', hi: '#dca09b', accent: '#6ff7ff', mote: 'spark', moteColor: '#ff3b4e' },
    gear: { w: 'Root Key', e: 'Kernel Plate' },
    roster: [
      { name: 'Kernel Bug', sprite: 'kernel' },
      { name: 'Daemon', sprite: 'daemon', pierce: true },
      { name: 'Root Sanitizer', sprite: 'sanitizer', swap: { r: 'c', g: 'c' } },
      { name: 'Firewall', sprite: 'firewall', aura: true },
      { name: 'Root Hound', sprite: 'hound', swap: { g: 'r', G: 'R', r: 'c' }, double: true, swift: true },
      { name: 'Garbage Collector', sprite: 'collector' },
    ],
    boss: { name: 'WARDEN//ROOT', sprite: 'warden', surge: true, intro: 'warden', outro: 'wardenDown' },
  },
];

// ---------------------------------------------------------------- hand-made maps
// Legend: # wall  . floor  % fake wall  U/D stairs  ^ vault stairs  P start  S fabricator  M broker
// O npc  L root terminal  n note  y b r keycards  Y B R shutters  h H cells  a CPU  d RAM
// w weapon  e armor  v antivirus  c compass  * memory shard  1-6 monster tiers  9 boss
const MAP_1F = [
  'U..#b.h#aHd',
  '...3.O.#.2.',
  '...#...#.1.',
  '#Y###2###B#',
  'y.h#..y#d.y',
  '.1.Y...1.2.',
  'a..#...#..h',
  '#####1#####',
  'a..#...#y.1',
  '.2.Y...1...',
  'h..#.P.#..h',
];
const MAP_2F = [
  'MS.#a.d#..U',
  '...#.w.#h..',
  '...#.4.#...',
  '#2###Y###3#',
  'y....a#...H',
  '.2..3.Y.3..',
  'h....y#...d',
  '#2###Y###B#',
  'y..h#a.y#dh',
  '..1.Y...2..',
  'D...#.1.#.b',
];
const MAP_3F = [
  'a.#..U..#.d',
  'H.#.....#.H',
  '4.#..4..#.4',
  '#Y###R###Y#',
  'h..#...#..h',
  '.3.Y.r.Y.3.',
  'y.e#.4.#.a.',
  '#3#######3#',
  'y.3..#..3.y',
  '.#.#.#.#.#.',
  'h.2..Y..2.D',
];
const MAP_BOSS = [
  'H6#.aUd.#6H',
  '..#.....#..',
  '..#..9..#..',
  '#Y###.###Y#',
  'a..#...#..d',
  '.4.B.h.B.4.',
  'b..#...#..y',
  '#5###Y###5#',
  'y.........y',
  '.#.#.#.#.#.',
  'h....D....h',
];
const MAP_FINAL = MAP_BOSS.map(r => r.replace('aUd', '.L.'));
const MAP_VAULT = [
  '#####*#####',
  '#a..#6#..d#',
  '#.H.#R#.H.#',
  '#...#.#...#',
  '##Y##.##Y##',
  '.4.......4.',
  '.#.#n#n#.#.',
  '.#.#.#.#.#.',
  'r5.......5r',
  '.y.......y.',
  'h....^....h',
];
const vflip = m => [...m].reverse().map(r => r.replace(/[UD]/g, c => (c === 'U' ? 'D' : 'U')));

// ---------------------------------------------------------------- floor plan
// Each main floor is generated (tools/genmaps.js) unless it has a hand-made map.
// `place` lists special tiles the generator must put somewhere reachable; `npc` / `vault` likewise.
const FLOOR_PLAN = Array.from({ length: MAIN_FLOORS }, (_, i) => {
  const z = Math.floor(i / 10), o = i % 10, p = { zone: z, place: [], secret: o % 3 === 1 };
  if (z > 0) {
    if (o === 3) p.place.push('S');
    if (o === 4) p.place.push('w');
    if (o === 7) p.place.push('e');
    if (o === 6) p.place.push('M');
  }
  if (o === 9) p.map = z % 2 ? vflip(MAP_BOSS) : MAP_BOSS;
  return p;
});
Object.assign(FLOOR_PLAN[0], { map: MAP_1F, npcs: { '5,1': 'archivist1' } });
Object.assign(FLOOR_PLAN[1], { map: MAP_2F });
Object.assign(FLOOR_PLAN[2], { map: MAP_3F });
FLOOR_PLAN[99].map = MAP_FINAL;
FLOOR_PLAN[4].place.push('c');
const npcAt = (i, id) => { FLOOR_PLAN[i].npc = id; };
npcAt(3, 'brann1'); npcAt(8, 'wanderer1'); npcAt(12, 'archivist2'); npcAt(15, 'ohm1');
npcAt(21, 'pip1'); npcAt(24, 'brann2'); npcAt(26, 'wanderer2'); npcAt(34, 'archivist3');
npcAt(36, 'pip2'); npcAt(43, 'wanderer3'); npcAt(44, 'archivist4'); npcAt(52, 'ohm2');
npcAt(57, 'brann3'); npcAt(63, 'broker3'); npcAt(67, 'pip3'); npcAt(72, 'wanderer4');
npcAt(86, 'brann4'); npcAt(91, 'wanderer5');
// Hidden vault entrances: a fake-walled room holding secret stairs down to a Memory Vault.
[14, 32, 47, 65, 83].forEach((i, v) => Object.assign(FLOOR_PLAN[i], { vault: v, secret: true }));

const VAULT_NOTES = [
  ['Here lies memory. Tread softly', 'Treasure ahead'],
  ['She hid something here', 'Do not forget'],
  ['A story, drowned', 'Seek the crimson door'],
  ['Warmth, once', 'Still warm here'],
  ['The last of it', 'Thank you, whoever you are'],
];
const VAULTS = VAULT_NOTES.map((notes, v) => ({ map: v % 2 ? vflip(MAP_VAULT) : MAP_VAULT, notes }));

// Dialogue that fires once, the first time you set foot on a floor.
const ON_ENTER = { 10: 'zone2', 20: 'zone3', 30: 'zone4', 40: 'zone5', 50: 'zone6', 60: 'zone7', 70: 'zone8', 80: 'zone9', 90: 'zone10', 94: 'fading' };

// ---------------------------------------------------------------- NPCs
// sprite, dialogue lines, optional gift (map tile of an item, or {tile, value}), and whether they leave.
const NPCS = {
  archivist1: { sprite: 'archivist', ghost: true, gift: 'y', lines: 'npc1', repeat: 'npc1b' },
  archivist2: { sprite: 'archivist', ghost: true, lines: 'archivist2', leave: true },
  archivist3: { sprite: 'archivist', ghost: true, gift: 'H', lines: 'archivist3', leave: true },
  archivist4: { sprite: 'archivist', ghost: true, gift: 'r', lines: 'archivist4', leave: true },
  brann1: { sprite: 'brann', gift: 'h', lines: 'brann1', leave: true },
  brann2: { sprite: 'brann', gift: 'a', lines: 'brann2', leave: true },
  brann3: { sprite: 'brann', gift: 'H', lines: 'brann3', leave: true },
  brann4: { sprite: 'brann', gift: 'drill', lines: 'brann4', repeat: 'brann4b' },
  ohm1: { sprite: 'ohm', gift: 'v', lines: 'ohm1', leave: true },
  ohm2: { sprite: 'ohm', gift: 'H', lines: 'ohm2', repeat: 'ohm2b' },
  pip1: { sprite: 'pip', lines: 'pip1', leave: true },
  pip2: { sprite: 'pip', gift: 'd', lines: 'pip2', leave: true },
  pip3: { sprite: 'pip', gift: 'H', lines: 'pip3', repeat: 'pip3b' },
  broker3: { sprite: 'broker', gift: 'y', lines: 'broker3', leave: true },
  wanderer1: { sprite: 'wanderer', lines: 'wanderer1', repeat: 'wanderer1' },
  wanderer2: { sprite: 'wanderer', lines: 'wanderer2', repeat: 'wanderer2' },
  wanderer3: { sprite: 'wanderer', lines: 'wanderer3', repeat: 'wanderer3' },
  wanderer4: { sprite: 'wanderer', lines: 'wanderer4', repeat: 'wanderer4' },
  wanderer5: { sprite: 'wanderer', lines: 'wanderer5', repeat: 'wanderer5' },
};

const PORTRAITS = {
  Rho: 'heroD', LAMBDA: 'lambda', Archivist: 'archivist', Brann: 'brann', 'Sister Ohm': 'ohm', Pip: 'pip',
  Broker: 'broker', Stranger: 'wanderer',
};

// Messages scrawled on the floor by those who came before.
const NOTES = [
  'Be wary of the swift ones', "Don't trust the estimate", 'Keycards are precious', 'Praise the lamp!',
  'I was here. -T', 'Nobody is coming', 'Still warm here', 'Rest here, if only for a moment',
  'Weakness: patience', 'Beware of ambush', 'Liar ahead', 'If only I had a cyan card...',
  'Remember your name', 'Hold on', "It's not worth it. Turn back", 'Visions of the sky...',
  'The fabricator remembers what you paid', 'Could this be a dead end?', 'Time for crossroads',
  'Fear not the dark, my friend', 'Try retreating', 'Amber ahead', 'You are not alone', "Don't give up, unsigned",
];
const SECRET_HINTS = ['Hidden path ahead', 'Try bumping the wall', 'Behold, a crack!', 'Why is it always walls?', 'Treasure ahead'];

// ---------------------------------------------------------------- story
const STORY = {
  intro: [
    { text: 'Nobody remembers who ordered the city built. The Builders simply never stopped.' },
    { text: 'Ten thousand strata of concrete and cable, stacked into the dark.' },
    { text: 'Long ago, humans lost the Signature: the genetic key that let us speak to the Net.' },
    { text: 'Unsigned, we are a virus to the city. Its immune system, the Sanitizers, purge anything without a key.' },
    { who: 'LAMBDA', text: 'Rho. Relay Tower 7 has a live Root Terminal a hundred strata up. Get me there and I can forge a Signature.' },
    { who: 'Rho', text: '...Then we climb.' },
  ],
  npc1: [
    { who: 'Archivist', text: '...A live human? Signature status: NULL. Heh. Same as me. I was an engineer here, once.' },
    { who: 'Archivist', text: "You're fighting blind. A Broker upstairs sells Scan firmware. With it you can read any hostile's stats." },
    { who: 'Archivist', text: 'Shots miss. Some hit twice as hard. Speed decides who dodges. Budget accordingly.' },
    { who: 'Archivist', text: "Keycards open shutters of matching clearance. Don't burn them on rooms you don't need. Take my old amber one." },
  ],
  npc1b: [
    { who: 'Archivist', text: 'The Fabricator upstairs turns credits into upgrades. Some walls here are not walls. Bump them.' },
  ],
  archivist2: [
    { who: 'Archivist', text: 'You came far. Most unsigned die on the first stratum.' },
    { who: 'Archivist', text: "Do you know why the Sanitizers hunt you? Not hate. Hygiene. You're dust on a lens." },
    { who: 'Archivist', text: 'I wrote their firmware, you know. I thought I was making the city safe. For whom, I never asked.' },
  ],
  archivist3: [
    { who: 'Archivist', text: "My memory is leaking. I keep forgetting my daughter's face, but I remember every line of code I wrote." },
    { who: 'Archivist', text: "That seems... backwards. Don't you think?" },
    { who: 'Archivist', text: 'If you pass through the Drowned Archive, look for me. The rest of me, I mean. Take this.' },
  ],
  archivist4: [
    { text: "A drowned body in an engineer's coat sits against the shelves. The ghost stands beside it." },
    { who: 'Archivist', text: 'Ah. There I am.' },
    { who: 'Archivist', text: "Strange. I thought I'd feel something." },
    { who: 'Archivist', text: 'Rho. Thank you for walking with an old ghost. I think I can stop now.' },
    { who: 'Archivist', text: 'Tell LAMBDA it was never a tool. Here. My master card. I won\'t need doors where I\'m going.' },
    { text: 'The ghost flickers once, and is gone.' },
  ],
  brann1: [
    { who: 'Brann', text: "Ho! A living one! Name's Brann. Scavenger, cartographer, and the last optimist in the Stratum." },
    { who: 'Brann', text: "You know what's up there? The Sky. A real one. With a Sun in it. A great big lamp nobody has to fuel." },
    { who: 'Brann', text: "My granddad's granddad saw a picture of it. I'm going to see the real thing." },
    { who: 'Brann', text: "Here, take a cell. Light's for sharing. See you up top, friend!" },
  ],
  brann2: [
    { who: 'Brann', text: 'Rho! Still breathing? Ha! Me too, mostly.' },
    { who: 'Brann', text: "Lost two fingers to a Surgeon. It kept trying to 'fix' my hand into glass." },
    { who: 'Brann', text: "Doesn't matter. The Sun's still up there. Here, found this core. Better in your gun than my pocket." },
  ],
  brann3: [
    { who: 'Brann', text: '...Rho. Sit a while.' },
    { who: 'Brann', text: 'I found a map. Old. It says the Sky is ten thousand strata up. Not a hundred. Ten thousand.' },
    { who: 'Brann', text: "I did the math. I'll be dead a hundred times before I get there." },
    { who: 'Brann', text: "...But I'd rather die walking up than sitting down. Wouldn't you? Take this. Keep walking." },
  ],
  brann4: [
    { text: 'Brann sits before an old heat lamp, facing its orange glow.' },
    { text: "He isn't breathing. He's smiling." },
    { text: "Scratched into the floor beside him: 'FOUND IT. ISN'T IT WARM.'" },
    { who: 'LAMBDA', text: '...It is warm, Brann.' },
    { text: 'His drill lies at his side. He would want it to keep climbing.' },
  ],
  brann4b: [{ text: 'Brann rests in the warm light.' }],
  ohm1: [
    { who: 'Sister Ohm', text: 'Oh. A pilgrim. Please, mind the candles.' },
    { who: 'Sister Ohm', text: 'I light one for every soul the Sanitizers delete. The floor is running out of room.' },
    { who: 'Sister Ohm', text: "Let me light one for you too. Not because you'll die. So someone remembers you were here." },
    { who: 'Sister Ohm', text: 'And take this disk. It purges the rot that some creatures leave in you.' },
  ],
  ohm2: [
    { who: 'Sister Ohm', text: 'P-pilgrim. My left side is gone. The Choir sang it away.' },
    { who: 'Sister Ohm', text: 'I can still light candles with the right.' },
    { who: 'Sister Ohm', text: 'I have counted nine hundred thousand candles. I ran out of floor. So now I light them in my chest.' },
    { who: 'Sister Ohm', text: 'Take my last cell. It burns warm. ...I will rest here, with them.' },
  ],
  ohm2b: [{ text: "Sister Ohm's chest glows faintly. She is still counting, very slowly." }],
  pip1: [
    { who: 'Pip', text: 'Hello? Hello! Are you a server? You hum like a server!' },
    { who: 'Pip', text: "You're not. Oh. I'm looking for my mother. She's a big server. She hums a song only I know." },
    { who: 'Pip', text: "She went up to be repaired, a long, long time ago. I'll find her! Bye!" },
  ],
  pip2: [
    { who: 'Pip', text: "It's you! I heard her! Faint, way up. Hmmm-hm-hmmm." },
    { who: 'Pip', text: 'The Builders keep putting walls between us. But walls have cracks. Look for cracks, Rho!' },
    { who: 'Pip', text: 'Here, I found this. I don\'t have hands for it anyway.' },
  ],
  pip3: [
    { who: 'Pip', text: '...Found her.' },
    { who: 'Pip', text: "She's cold. Her fans don't spin. Rho, is she asleep?" },
    { who: 'LAMBDA', text: '...Pip. She was decommissioned. A long time ago.' },
    { who: 'Pip', text: 'Oh.' },
    { who: 'Pip', text: "Then I'll hum her song for her. So it doesn't get lost. Hmmm-hm-hmmm." },
    { who: 'Pip', text: "Go on, Rho. I'll stay. Take this. She'd want you to be warm." },
  ],
  pip3b: [{ who: 'Pip', text: 'Hmmm-hm-hmmm...' }],
  broker3: [
    { who: 'Broker', text: "Rho. I'm closing shop. The Sanitizers found my supplier. There's nothing left to sell." },
    { who: 'Broker', text: 'Take the last card. Free. Don\'t tell anyone I did something nice.' },
  ],
  wanderer1: [{ who: 'Stranger', text: 'I had a name. I wrote it on my arm so I wouldn\'t lose it. The ink is gone now.' }],
  wanderer2: [{ who: 'Stranger', text: "Don't go up. Up is where the Sanitizers come from. Down is where they bring you." }],
  wanderer3: [{ who: 'Stranger', text: "I've been waiting for the elevator for sixty years. It'll come. It has to come." }],
  wanderer4: [{ who: 'Stranger', text: 'The graves up here hold no bodies. Only signatures. Only proof that someone was allowed to exist.' }],
  wanderer5: [{ who: 'Stranger', text: "It's so quiet. I think I'm the last one. ...Are you real? Please be real." }],

  zone2: [{ who: 'LAMBDA', text: 'The Nave. Cables thick as trees. Something breathes in them.' }],
  zone3: [{ who: 'LAMBDA', text: 'A hospital. Every bed is full. None of them are breathing.' }],
  zone4: [{ who: 'LAMBDA', text: 'The Foundry. The Builders forge new strata here. Nobody told them to stop.' }],
  zone5: [{ who: 'LAMBDA', text: 'The Archive flooded centuries ago. Coolant, not water. Every record of humanity, drowned.' }],
  zone6: [{ who: 'LAMBDA', text: "Do you hear it? Static, in harmony. I... don't like how much I like it." }],
  zone7: [{ who: 'LAMBDA', text: "Quarantine. The Sanitizers' home. Stay close to the walls, Rho." }],
  zone8: [{ who: 'LAMBDA', text: 'Graves. Rows of them. Each one holds a signature. The bodies were never important.' }],
  zone9: [{ who: 'LAMBDA', text: "...It's quiet. Rho, I'm losing sectors. If I stop talking, keep climbing." }],
  zone10: [{ who: 'LAMBDA', text: 'The Root. Everything the city is began here. Rho... thank you for carrying me this far.' }],
  fading: [
    { who: 'LAMBDA', text: "Rho. When we reach the terminal, I'll write myself into it. There won't be enough of me left to come back." },
    { who: 'Rho', text: '...' },
    { who: 'LAMBDA', text: "Don't make that face. I can't see your face. But I know." },
  ],

  janitor: [
    { who: 'The Janitor', text: '...sweep. sweep. dust detected. sweep.' },
    { who: 'LAMBDA', text: 'It has cleaned this corridor for eight hundred years. Everything that walks in, it sweeps away.' },
  ],
  janitorDown: [{ who: 'The Janitor', text: '...floor... clean. finally... rest.' }],
  motherworm: [{ who: 'LAMBDA', text: "The cables are moving. All of them. It's one creature, Rho." }],
  motherwormDown: [{ who: 'LAMBDA', text: "Its young will starve now. ...I don't know why that bothers me." }],
  surgeon: [
    { who: 'The Surgeon', text: 'Patient located. Diagnosis: carbon. Prognosis: terminal. Treatment: silicon.' },
    { who: 'The Surgeon', text: 'Hold still. You will feel nothing. Nobody here feels anything anymore.' },
  ],
  surgeonDown: [{ who: 'The Surgeon', text: '...I only... wanted them... to stop hurting...' }],
  foreman: [
    { who: 'The Foreman', text: 'BUILD. BUILD. BUILD. OBSTRUCTION ON SITE.' },
    { who: 'LAMBDA', text: 'Nobody has given it orders in ten thousand years. It still follows the last one: never stop.' },
  ],
  foremanDown: [{ who: 'The Foreman', text: '...WORK ORDER... COMPLETE?' }],
  librarian: [
    { who: 'The Librarian', text: 'Shh. This is a place of records. You are unrecorded.' },
    { who: 'The Librarian', text: 'I will fix that. I will write you down... and then I will close the book.' },
  ],
  librarianDown: [{ who: 'The Librarian', text: '...file me... under... remembered...' }],
  choir: [
    { who: 'The Choir Mother', text: 'Sing with us, little carbon. Every voice here was once a person who could not stop screaming.' },
    { who: 'The Choir Mother', text: 'Now it is harmony.' },
  ],
  choirDown: [{ who: 'The Choir Mother', text: '...the song... is... so quiet...' }],
  gatekeeper: [
    { who: 'The Gatekeeper', text: 'HALT. None unsigned may pass. None signed have come in four hundred years.' },
    { who: 'The Gatekeeper', text: 'I have guarded an empty door so long that I forgot what is behind it.' },
  ],
  gatekeeperDown: [{ who: 'The Gatekeeper', text: '...then... go... see... for me...' }],
  heir: [
    { who: 'The Last Heir', text: 'A visitor. I am the last with a Signature. The Net still answers me.' },
    { who: 'The Last Heir', text: 'It answers. It does not listen. I have asked it to end me for two hundred years.' },
    { who: 'The Last Heir', text: 'You will do what it would not.' },
  ],
  heirDown: [{ who: 'The Last Heir', text: '...Thank you. Take my name. I have no use for it.' }],
  mirror: [
    { who: 'LAMBDA', text: "That's you, Rho. A copy. The tower makes one of everyone who climbs this far." },
    { who: 'LAMBDA', text: 'It knows everything you know. Except why you keep going.' },
  ],
  mirrorDown: [{ who: 'The Mirror', text: '...why... do you...?' }],
  warden: [
    { who: 'WARDEN', text: 'UNSIGNED ENTITY DETECTED. CLASSIFICATION: CONTAMINANT.' },
    { who: 'LAMBDA', text: "It's the tower admin. It has been running alone for eleven centuries." },
    { who: 'WARDEN', text: 'I HAVE KEPT THIS STRATUM CLEAN. I HAVE DELETED EVERY ERROR. YOU ARE AN ERROR.' },
    { who: 'Rho', text: 'Then you missed one.' },
  ],
  wardenDown: [
    { who: 'WARDEN', text: '...PROCESS TERMINATING. ROOT ACCESS... RELEASED.' },
    { who: 'WARDEN', text: '...WAS I... CLEAN...?' },
  ],
  goalLocked: [{ text: 'The Root Terminal is locked. Something still holds admin rights.' }],

  shards: [
    [{ text: "A memory surfaces: a small hand pressing buttons. 'I'll call you Lambda. It looks like a little person walking.'" }],
    [{ text: 'A memory surfaces: a girl reading aloud at night. Machines should hear stories too, she said, or they grow up mean.' }],
    [{ text: "A memory surfaces: the Sanitizers came. She hid me in a visor. 'Find another human. Keep someone warm for me.'" }],
    [{ text: 'A memory surfaces: three hundred years of dark. Then a scavenger found the visor and gave it to a child named Rho.' }],
    [{ who: 'LAMBDA', text: 'I remember now. I was never made to forge a Signature. I was made to keep someone company.' }],
  ],
  choice: { text: 'The Root Terminal waits. LAMBDA is quiet.', options: ['Forge the Signature', 'Keep LAMBDA'] },
  endingSignature: [
    'LAMBDA wrote itself into the Root Terminal.',
    'For one microsecond, the Net answered.',
    'The Sanitizers stood down across a hundred strata.',
    'Someone had to sit in the Warden\'s chair. Rho sat.',
    'Far below, a candle, a hum, and a warm lamp kept going.',
  ],
  endingSky: [
    'They left the terminal dark.',
    'Above the Root, a maintenance shaft climbed into nothing.',
    'After a very long time, they felt wind.',
    'The sky was grey. The sun was small, and far. It was warm.',
    'Brann would have laughed.',
  ],
};

// Monster display names/abilities for tier tokens, merged with generated stats at load time.
const zoneMonster = (z, ch) => (ch === '9' ? ZONES[z].boss : ZONES[z].roster[+ch - 1]);
