'use strict';
// Embeds assets/sfx/<name>_<n>.ogg into js/samples.js as base64, grouped by name, so the game runs from file://.
// Sources and licenses: assets/sfx/CREDITS.txt.
const fs = require('fs'), path = require('path');
const dir = path.join(__dirname, '../assets/sfx'), out = {};
for (const f of fs.readdirSync(dir).filter(f => f.endsWith('.ogg')).sort()) {
  (out[f.replace(/_\d+\.ogg$/, '')] ??= []).push(fs.readFileSync(path.join(dir, f)).toString('base64'));
}
fs.writeFileSync(path.join(__dirname, '../js/samples.js'),
  `'use strict';\n// CC0 sound effects (assets/sfx/CREDITS.txt), embedded so the game runs from file://. Generated by tools/gensamples.js.\nconst SAMPLES = ${JSON.stringify(out)};\n`);
console.log(Object.entries(out).map(([k, v]) => `${k}:${v.length}`).join(' '));
